font-patcher

Ref: https://github.com/ryanoasis/nerd-fonts/issues/19

font-patcher: only load Pomicons.otf with --pomicons

---

gotta-patch-em-all-font-patcher!.sh

* It now runs on OS X
* find incompatibility is fixed
* FontForge from Homebrew can be found by Python
* It checks for FontForge availability and directs to installaction
instructions if it's not found
* It is much shorter

Patcher Script clean up

---

font-patcher

Reference issue: https://github.com/ryanoasis/nerd-fonts/issues/68

Use "powerlineSymbols" as 4th arg.

---

patched-fonts/Hack/README.md

The entire file appeared twice, like someone did a select-all & paste.
N/A
Deletes text so that there is only one copy in the file
N/A
Just saw the text

Remove redundant repeated text

---

readme.md

Fixed Issue #117
_Made some adjustments to the values presented in the "Features" section._

Updated 'Features' section counts

---

bin/scripts/archive-fonts.sh
bin/scripts/build-latest-py3-version.sh
bin/scripts/fpfix.py
bin/scripts/generate-casks.sh
bin/scripts/generate-css.sh
bin/scripts/generate-fontconfig.sh
bin/scripts/gotta-patch-em-all-font-patcher!.sh
bin/scripts/release.sh
bin/scripts/standardize-and-complete-readmes.sh
bin/scripts/upload-archives.sh
bin/scripts/version-bump.sh

Added [Nerd Fonts] prefix to all script output per issue #119
- [x ] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x ] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ)
- [x ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
Adds a prefix to all script output
Closes #119

add [Nerd Fonts] prefix to script output

---

readme.md

Just tries to format command in README.
Not necessary.
No.
No.
No.

Remove trailing spaces in shell command

---

.github/ISSUE_TEMPLATE.md

Fix the wiki link in the issue template.
Fixes #174.

Fix wiki link in ISSUE_TEMPLATE.md

---

changelog.md
font-patcher
readme.md

* @AndreLGava changed his username to @AndreLZGava, updated references
* fixed a few typos in font-patcher

Fixed typos

---

readme_cn.md

I create a Chinese version read me file and I just complete the translation of introduction.
I create a Chinese version read me file and I just complete the translation of introduction

I create a Chinese version read me file and I just complete the translation of introduction

---

.travis.yml
readme.md

I setup Travis-CI (closes #120) to run [ShellCheck](https://github.com/koalaman/shellcheck). I could only set it up against my fork, so you will have to create an account on [Travis](https://travis-ci.org/) and point it to your repo. All the configuration is in .travis.yml
This pull request adds continuous integration with Shell linting using [ShellCheck](https://github.com/koalaman/shellcheck). It does not resolve any of the issues ShellCheck found.
Not applicable.
#120

Add shellcheck ci

---

readme_tw.md

I've created a README of Traditional Chinese(zh-tw) version.
Created a README of Traditional Chinese(zh-tw) version.

Add readme of zh-tw version

---

readme.md

- [ x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [ x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
Fixed some fonts names in Patched Fonts section in readme.md.
Check the Fira, Hasklig, Hack, Share and Terminus fonts names in Patched Fonts section.
It is not necessary
It is not necessary
It is not necessary

Fixed some fonts names

---

readme_fr.md

I create a french readme file
A french readme file is added

French Readme file

---

readme_pl.md

Added file readme_pl - Polish translation of the readme file
This PR adds Polish translation of the readme file
Go to: nerd-fonts/readme_pl.md
No changes in scripts
#118 
Go to: nerd-fonts/readme_pl.md

Add readme_pl translation

---

readme_fr.md

Remove "There is also a [font patcher](#font-patcher) available if your desired font isn't already patched."
The french traduction is already on the file "Un [généreur de polices](#font-patcher) est aussi disponible si vous souhaitez ajouter une police non présente."

Remove text in english

---

readme.md

See the [according](https://github.com/ryanoasis/nerd-fonts/issues/352) issue, developer allows us to use the name. :hugs:

Change Fura to Fira

---

patched-fonts/BigBlueTerminal/readme.md

Fix formatting

---

readme_ko.md

I translated the readme document into Korean.
This PR adds a Korean translation of readme.md
N/A
N/A
#118 
N/A

Add Korean translation of readme.md

---

readme_uk.md

To cover issue #118 (Add internationalization and localization support to readme)
Closed issue #390 added to repo new file readme_uk.md
According to http://www.localeplanet.com/icu/uk-UA/index.html will be uk language code.
added new file readme_uk.md with translation
Negative
Negative
issue #390 
Negative

Translate readme to Ukrainian #390

---

readme_ptpt.md

Hi 👋. I've translated the README.md to Portugal Portuguese (a little different from Brazilian Portuguese).
Added the file readme_ptpt.md to the project's root with the translation.
N/A
N/A
#118 
N/A

Added pt-pt language to readme.md

---

readme.md
readme_cn.md
readme_es.md
readme_fr.md
readme_it.md
readme_ja.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md

Update link to cheat sheet in readme's
Visit https://nerdfonts.com/#cheat-sheet, which is an anchor that points nowhere, and then visit https://www.nerdfonts.com/cheat-sheet.

Update link to cheat sheet in readme's

---

readme.md

Small spelling correction in README.
Documentation correction
No
Match spelling used https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hermit
N/A
N/A

spelling: hermut -> hurmit

---

src/readme-rfn-addendum.md

Fix typo: partcular -> particular see #550

Fix typo: partcular -> particular #550

---

_data/fonts.json

Just a few things I ran into. Thanks for your work!
Changed some descriptive text for spelling.
- [* ] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [ *] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ *] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
Just text fixes for the website.
No testing needed.

Spelling fixes

---

readme_hi.md

Signed-off-by: Harshal Rathore <harshalrathore2014@gmail.com>
Added the Hindi version of README.md
Partially solves #118 
Don't know
Null
Null
Null

Added Hindi version of readme.md.

---

readme_pl.md

Make readme_pl.md better.
Made readme_pl.md
Makes it so non-existent polish words are replaced with other words that fit well.

Replace non-existent polish words with other words that do exist in readme_pl.md.

---

LICENSE

Fix typo: orignal -> **original**

Fix typo: orignal -> original

---

readme.md

Added two fonts to the AUR section of the README
These are currently the 3rd and 4th most popular Nerd Fonts packages in the AUR respectively, and I felt they should be included.
See description.

List AUR packages for Jetbrains & Victor Mono

---

.github/workflows/font-patcher.yml

Fontforge got a new release :tada: 
Make sure we can work with that.
Test the `font-patcher` script with the newest `fontforge` release, additionally.

CI: Include newest fontforge release in tests

---

readme_tw.md

_Update the zh-tw documentation._
Update the zh-tw documentation

doc: update zh-tw translation documentation

---

_posts/2017-01-02-features.md

... Unless you're expecting more topics to match in the future?
Old:
https://github.com/search?q=nerd+fonts&type=Topics
New:
https://github.com/topics/nerd-fonts
---
PS: Not particularly a fan of having the website live in a branch, mostly just because it means it can't be searched via the GitHub website.

Direct GitHub link

---

.github/ISSUE_TEMPLATE/bug_report.md

This PR fixes indentation of `Your Setup` section and standartizes comment tags.

Improve bug report issue template

---

.github/workflows/release.yml

Fontforge had a new release. There is no particular error it fixes that we suffer on, but keeping up to date?
Build the next release with FF Jan-2023.

CI: Update release to Fontforge January 2023 Release'

---

readme.md

Update the JetBrains mono version in the readme that did in: https://github.com/ryanoasis/nerd-fonts/commit/c6b3b0841cc754e14b49c8a5d001baa7f4b67ecf

update jetbrains mono version

---

bin/scripts/test-fonts.sh

Add run comment

---

readme.md
src/unpatched-fonts/Iosevka/README.md
src/unpatched-fonts/Iosevka/copyall.sh
src/unpatched-fonts/IosevkaTerm/README.md
src/unpatched-fonts/IosevkaTerm/copyall.sh

ttf-iosevka-22.1.0.zip
ttf-iosevka-term-22.1.0.zip
[how]
Download relevant archives and put both into ~/Downloads/iosevka Run copyall.sh on both dirs.

Update Iosevka to 22.1.0

---

readme.md

Use more concise link for finding Nerd Fonts Arch Linux packages.

Use nerd-fonts group link for Arch packages

---

changelog.md

Fixed a typo mistace -> mistake
Typo fix

Fix a typo

---

readme_cn.md
readme_tw.md

Updated the patched fonts table in the zh-cn& zh-tw docs.
Updated the patched fonts table in the zh-cn& zh-tw docs:
- readme_cn.md
- readme_tw.md

docs: update fonts table for translation docs

---

contributing.md

_Fix typo found while reading_

Fix typo: exeucte -> execute

---

readme_es.md

_Update Spanish translation on readme_es file._
- Updates `readme_es.md` to pair with main readme file.
- Fix typos
File is not updated.
Originally I wanted to make the TOC working but, didn´t work as expected so here it's with only the essential changes.

Update readme_es.md file

---

readme.md

Append a explanation on how to automatically download the latest release of a given font.
The new option should mainly be used inside scripts.

Add "curl latest release" to download options

---

_includes/css/nerd-font-tweaks.scss

Fix wrong small version of all-icons-divider

---

readme.md

Update Arch Linux repository in readme.md. It's now in [extra] repository.

 Update Arch Linux repository in readme.md

---

bin/scripts/test-fonts.sh

_ Updates the range for Pomicons and Font Logos fonts._
Updates range of fonts
Run the script
I forget to update in #1427

Update end codepoints on testing script

---

.all-contributorsrc
CONTRIBUTORS.md

All contributors/add madmaxieee

---

readme.md

Updated README to add the font "SF Mono" to the "Other good fonts to patch" list.

Added another good font to patch (SF Mono)

---

changelog.md

Typo fixes, no other changes
Couple of typo fixes
Testing is not needed

Typo fixes in changelog.md

---

.all-contributorsrc
CONTRIBUTORS.md

Allcontributors again broken (does not create a PR), but the branch is there.
Manually doing the PR.

All contributors/add oktoling
