ryanoasis/nerd-fonts

install.sh

I've created an install script which uses fc-cache. Should work atleast on Ubuntu; haven't tested in other distros.

Install script for Ubuntu

---

readme.md

@ryanoasis 
Can you provide information about how to install it best?
The Ubuntu repos do not provide it (20120731.b-5+b3 being the latest in Debian/Ubuntu).
Is manually installing the way to go?
There is no package on PyPI, is there?
*Edit*: the Fontforge book has install instructions, and I've added a link to it.

readme: mention python-fontforge minimum version

---

font-patcher

These small modifications to the font patching script take the separate font styles into account when generating the font family and font name of the generated fonts. This ideally consolidates all of the fonts under a single font family each as a unique font style when the patched fonts are installed.
I'm not fully aware of the standards used with regards to the dashes in the different strings that are assumed in this pull request so additional normalization may need to be done in order to prevent these changes from causing problems on fonts that have non-standard or incorrect metadata. I'm happy to put research into this if this is a desired modification to the script.

Consider font style when generating familyname and fontname

---

install.sh

It now has more options than copying all patched files or one font’s
patched font files.
In short, you can choose which patchset, which compatibility, which
method (copy or symlink), and which fonts you want to install, and sets some
sensible defaults for these options whilst not breaking past behaviour much.
Features that break with past behaviour:
* Installs fonts to a subdirectory of the user's fonts directory.
* Only installs the 'Complete' version of a font by default.
* Prefers OTF version if there are both OTF and TTF versions.
I did my best to follow the options convention of the font patcher script.
I wrote this on a Debian box, I haven't tested this on OS X.

Better installation script

---

patched-fonts/3270/LICENSE.txt

Missing license file. The 3270font project builds upon work that dates back to the 1980's and requires distribution of the license file (updated, if needed) along with derived works. From the license, "Redistributions in binary form must reproduce the above copyright notice".
Add a missing license file
N/A
Binary distribution needs referred license
112
N/A

Add license file for 3270font, fix #112

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Fix link to FAQ in GitHub files.

Fix FAQ links in .github/

---

readme.md

I found a markup problem in the readme.
I fixed the markdown by adding the html directly.
Fix markup
see the diff :)

Fix markdown by forcing html

---

font-patcher

Fedora's fontforge modules only work on Python 3. The small changes in
this patch make font-patcher work on Python 3 so I can run the script on
Fedora (26 at least, I don't know about older versions)

Make font-patcher Python 3 compatible.

---

font-patcher

Fixed fontforge errors in `font-patcher`.
Fixes fontforge errors pertaining to language and selection properties where fontforge doesn't seem to accept certain raw strings (it thinks they aren't strings). Wrapping them in `str()` fixed it.
Run `font-patcher`
Was trying to patch some fonts and got these errors.
@ryanoasis/nerd-fonts#164

Fix font-patcher python errors.

---

font-patcher

Add " Mono" to the font family name when generating single-wide fonts.
Run `./font-patcher` with the `-s` flag and check the generated fonts.
Fixes #176.

Change the font family name for mono fonts

---

font-patcher

If you try to run the `font-patcher` script outside of its directory, it will fail to open the files.
Allows the script to be run from any directory.

Open files relative to the script's directory

---

install.sh

Allows execution 'sudo ./install.sh -S <fonts>' which will use the
global system install path rather than the users local path.  May
also use --install-to-system-path as a long version.  Also allows 
-U (or --install-to-user-path) to explicitly set to install to users path, 
but that is the default so just there for completeness.
I made sure to support and test both MacOS and Linux.
Enhances the install.sh script to support installing to the global system font path.
Run the ./install.sh command like so:  sudo ./install.sh -S Hack then check the global system font
path for a …

Added support to install fonts to global system path.

---

readme.md

Minor changes to readme.md
- Remove Project History ToC link
- Fix anchor name in Project Motivation ToC link

Fix Project Motivation ToC link in readme.md

---

font-patcher

When running `fontforge -script font-patcher ...`, glyph files in src/glyphs are not located, emitting these messages:
```
Traceback (most recent call last):
지정된 파일 original-source.otf 은 존재하지 않습니다. (meaning the file does not exist)
File "font-patcher", line 707, in <module>
symfont = fontforge.open(__dir__+"/src/glyphs/"+patch['Filename'])
EnvironmentError: Open failed
```
The cause of the error was cured by setting `__dir__` to explicit absolute path.
fix `__dir__` to have the correct path, not empty in script "font-patcher"

fix '__dir__' set to empty

---

install.sh

Installation would fail if you did not first cd in into the nerd-fonts
directory before running install.sh as $nerdfonts_root_dir referenced
${PWD} which is the path your shell is into when calling the script,
not the basepath of the script, parent of "patched-fonts".
Make the install script callable from everywhere.
Run the install script from outside the nerd-fonts root dir.
NA
NA
NA
Thanks for the great work guys, cheers !

Make the install script callable from everywhere

---

10-nerd-font-symbols.conf

Added `monospace` family to font config.
This is needed to make "Monospace Regular" (aka DejaVu Sans Mono) work in gnome terminal.

Add monospace font family to config

---

install.sh

Resolves #218 
Modifies `install.sh` to treat a return code of 1 from `fc-cache` as a success (and pass 0 through as the return code from the script)
Execute `install.sh` and verify exit code ($?) is 0 on success.
#218

Treats fc-cache return of 1 as success

---

bin/scripts/lib/i_weather.sh

Fixes a typo int he test command, changing the underscore in `_n` to a hyphen `-n`.
The underscore caused the test to fail.
- [✅] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [✅] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [✅] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [✅] Scripts execute without error (if necessary):
- [✅] Extended the README and documentation if necessary, e.g. You added a new font please …

Fix test flag for $__i_weather_loaded

---

index.html

switched google fonts link to https, to get rid of blocking Mixed Content error (at least for Chrome 67)
changes goole fonts url from http to https
Load the github page and check if font loads correctly

switched google fonts link to https

---

readme.md
src/readme-per-directory-addendum.md

Fura Code doc improvment
related discussion in ticket https://github.com/ryanoasis/nerd-fonts/issues/248

Document which Fura Code variant to use for ligatures

---

readme.md

This pull request provides a change on tap name in installation guide for macOS users since Caskroom/fonts has been deprecated.
https://github.com/caskroom
Just update on README
No tests are needed.

Change tap name

---

font-patcher

changed glyph iteration method to fontforge.font.glyphs(), as fontforge.font.selection.byGlyphs was read only. removed ttf condition on setting all glyph widths to the same. moved another glyph width adjustment to put it after bearing adjustments
patches font-patcher
patch any font with any options with font-patcher
not all glyphs were being set the the same width, this should fix it
277: tested, fixed the issue
270: tested, fixed the issue
269: tested, fixed the issue
268: tested, fixed the issue
263: seems possible

fix monospace/overlap problem

---

font-patcher

put most code in functions
broke some functions into multiple functions
put most functions in a class
put 2 blank lines between all functions
renamed some variables/parameters for to make their purposes more clear
renamed some functions to make their purposes more clear
aligned some groups of lists, dicts, etc elements for better readability
changed some lists and dicts to put their elements on separate lines
changed conditions var == False to var is False
removed extra commas in lists and dicts
removed whitespace in brackets, braces, etc that touches the brackets, braces, etc
added whitespace after commas in lists and dicts
added whitespace around operators
changed FIXME and TODO to uppercase
added 4 NOTEs in regards to questions i had
changed unneeded returned variables to underscores …

Refactor font patcher

---

install.sh

This fixes the shellcheck error. Running on my laptop, `exit -1` results in an actual return code of 255, so make that explicit.
This should help with the Travis CI failures.

Fix the negative error number

---

patched-fonts/install.ps1

The PowerShell script "install.ps1" from the repository of Powerline Fonts works on Nerd Fonts too with the instruction( https://medium.com/@slmeng/how-to-install-powerline-fonts-in-windows-b2eedecace58 ).
Adding PowerShell script to let Windows have one-key-installation.
Follow the instruction here, and see if the fonts were installed:
https://medium.com/@slmeng/how-to-install-powerline-fonts-in-windows-b2eedecace58
Since there were no one-key-installation script for Windows in the repository before, I've made some 
attempts and found that this script works just fine.
Issue #223

Adding PowerShell script to let Windows have one-key-installation.

---

chocolatey/Pipfile
chocolatey/Pipfile.lock
chocolatey/README.md
chocolatey/base.nuspec
chocolatey/fonts.yml
chocolatey/generate_packages.py
chocolatey/tools/Add-Font.ps1
chocolatey/tools/Remove-Font.ps1
chocolatey/tools/chocolateybeforemodify.ps1
chocolatey/tools/chocolateyinstall.ps1

Chocolatey package generation scripts. Added a few fonts that I use. Rest can be added as described in the README.
- [] Scripts execute without error (if necessary):
Adds chocolatey packages and respective generating scripts.
- Run the `generate_packages.py` to generate chocolatey packages for the fonts.
- Go inside any generated folder and run `choco install <font-id> -s .`
- e.g: `choco install hasklig-nerd-font -s .`
- Fonts should get installed successfully
Chocolatey is a package manager for windows. Easy installation of fonts using the commands like `choco install …

Added chocolatey install scripts

---

.gitignore

When using the patched-fonts directory directly with let say Gnome, a bunch of *.uuid files are created and polluting the git environment with new files. This make sure those are ignored.
- [ * ] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [ * ] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ * ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [ N/A ] Scripts execute without error (if necessary):
- [ N/A ] Extended …

ignore *.uuid files

---

font-patcher

- [] Extended the README and documentation if necessary, e.g. You added a new font please update the table
Renaming Anka/Coder font to AnaConder, so the script not run into an error because of the / in the name and comply with SIL Open Font License (OFL)

Extend FontNameReplacements for Anka/Coder

---

readme_es.md

Added a full translation of the readme.md file.
_New translation, to Spanish, of the readme.md file._
New Spanish translation of the readme file.

Add Spanish translation of readme.md

---

patched-fonts/Agave/readme.md

Update the formatting to use Markdown format to display correctly on GitHub
I figured this step wasn't necessary for this change
Improves the formatting of documentation with appropriate format
Check the Readme file on GitHub

Improve formatting of Agave Readme

---

_posts/2017-01-02-features.md

The link to the fish shell on the home page points to vim-devicons. This PR fixes it.

Fix link address

---

readme_ja.md

This adds Japanese version of README.

Add Japanese translation for README

---

readme.md

Package nerd-fonts-complete-mono-glyphs in AUR is out of date since 2017-10-03. I added a little text next to it in readme.

Mark an outdated AUR font package

---

patched-fonts/FiraCode/readme.md

fixes img src url for elixir screenshot in readme
fixes img src url for elixir screenshot in readme

fix src in elixir screenshot img tag

---

readme_it.md

This adds the Italian version of the README file for advancing the #118 issue.
I have added the `Caskaydia Cove Nerd Font`line in the available font table even if in master the links are broken. Is better to keep that out?

Add Italian translation for README

---

.travis.yml

I fixed CI's error.
shellcheck comes standard with travis. Therefore, there is no need to install it explicitly. 
With this patch, lint will work properly.
> https://github.com/koalaman/shellcheck/wiki/TravisCI
Fix CI's error.
Nothing. Please see travis-ci's status.
> https://travis-ci.org/github/kazukazuinaina/nerd-fonts/builds/699502908
It ispassing status in my fork repo.

[fix] CI's error

---

font-patcher

I keep seeing this warning when running `font-patcher`, and realised this is a relatively simple fix. This property expects and `int`, but a `float` is passed and implicitly cast.
This squelches the deprecation warning, and keeps the code future-proof too.
```
/nerd/font-patcher:823: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
glyph.left_side_bearing = 0.0
/nerd/font-patcher:825: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
glyph.right_side_bearing = 0.0
```
- If any of the scripts were modified they have been tested and execute without …

Change bearing to `int`, since an int is expected

---

_posts/2017-01-03-downloads.md

This appears to be the canonical URL these days. The `app.` subdomain has become a redirect page (with a message explaining that).

Fix font preview link

---

patched-fonts/Iosevka/readme.md

[The cask](https://github.com/robertgzr/homebrew-tap) has moved, this change updates the `brew tap` command to be correct, and resolves the following error:
```
Error: caskroom/fonts was moved. Tap homebrew/cask-fonts instead.
```
- [x ] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x ] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x ] Scripts execute without error (if necessary):
- …

Fix homebrew cask tap command

---

readme.md

Using a recent version of Homebrew on Mac OSX, the installation instructions don't work, this change updates the instructions in the README to work with newer versions of Homebrew.
**Steps to reproduce:**
1. install Homebrew version 2.7.0
2. run CLI command `brew cask install font-hack-nerd-font`
**Expected result:** ❔ Nerd Fonts would be installed
**Observed result:** ❌ Error from Homebrew with CLI output `Error: Calling brew cask install is disabled! ...`
**Solution:** ✅ Use the CLI command `brew install --cask font-hack-nerd-font` instead
- ~`N/A` Scripts execute without error (if necessary):~
Updates README docs only.
_CLI output pictured below:_

Updated command for Mac OSX Homebrew install

---

patched-fonts/Terminus/terminus-ttf-4.40.1/readme.md

Fix typo: partcular -> particular

---

font-patcher

The font patcher now takes the style ("Italic", "Regular", etc) from the filename if it's longer (contains more information) than the "subfamily".
Updates the font patcher's algorithm for detecting the style (Italic, Regular, etc) in the font's Postscript name, so that it's more accurate.
When I first tested this with IBM Plex Mono 5.3.1, I could confirm that it fixes fixes #257 by successfully giving each generated font a unique Postscript name.
I have since tested it with VictorMono and JetBrainsMono. I have also imported all three into Font Book on OS X, and confirmed that this pull request does, indeed, resolve the issue.
- …

Take the style from the filename if it's longer than the subfamily (fixes #257)

---

contributing.md

Following issue #225 it seems fontforge has updated how it behaves after installing. For a consistent experience across 
various operating systems (Ubuntu, macOS, etc), it seems we get better results by pre-pending `fontforge --script ..` 
before running the `font-patcher` script.
Updates the Contributing.md docs.
Verify that e.g. `fontforge --script ./font-patcher src/unpatched-fonts/Hasklig/Regular/Hasklig-Regular.otf --complete` also works locally for you.
If not, we should include both with and without.
While trying to follow the contribution instructions, the invocation of …

Update contribution instructions with `fontforge --script`

---

patched-fonts/Gohu/readme.md

Replaced with link to gohu.org
Replaced the link in the documentation
Fix the documentation - Unfortunately Github also fixed the line endings to WinDOS style - sorry.
Read the readme and find a link to gohu.org
No
none

link to gohu.eu is dead

---

.dockerignore
.github/workflows/docker-release.yml
Dockerfile
bin/scripts/docker-entrypoint.sh
readme.md

The changes introduce Docker support for Nerd Fonts.
- Adds a `Dockerfile` alongside `.dockerignore` and a shell script that serves as the entrypoint of the container
- Defines a GitHub Actions workflow for continuous deployment of the image. Of course, any other CI/CD tooling of your choice may be used
- Extends the README with text passages on how to use the image
- References a Docker Hub repository I have created for the project (`nerdfonts/patcher`)
The PR requires some follow-up work:
- Invitation of the project's owner to the Docker Hub organization and transfer of its …

Docker support

---

readme.md

The command
```sh
brew cask install font-hack-nerd-font
```
doesn´t work with the latest version of `brew`.
More on [stackoverflow](https://stackoverflow.com/a/66081492/8848515).
Update the readme

Brew cask install update

---

font-patcher

allow setting custom glyph storage directory
Useful for allowing installation in system wide
locations as a package from the package manager.
This way the script can be installed in /usr/bin
and glyphs can be in /usr/share/nerd-fonts/glyphs.
Signed-off-by: Aisha Tammy <floss@bsd.ac>

allow setting custom glyph storage directory

---

readme.md

To prevent surprises as described in [#608](https://github.com/ryanoasis/nerd-fonts/issues/608).
I've taken the liberty to adjust the formatting a bit beneath bullet points like so:
---
* Before
Some text here and...
```
./also.sh --some "code"
```
* After
Some text here and...
```
./also.sh --some "code"
```
---
Feel free to revert this if you prefer the prior look.

Add AppImage patching instructions to Readme

---

readme.md

Sparse-checkout was introduced in git v2.25, and improved in v.2.26 with the add mode. This makes it possible to only clone one font instead of the entire repository. I added a description in the README.
Add documentation
By performing the steps added
I wanted to to use git but did not want to download the entire repo
n/a
n/a

Add sparse-checkout example to only clone one font

---

install.ps1
patched-fonts/install.ps1
readme.md

Fixes Powershell install script for Windows
- Be on Windows
- `./install.ps1 Hack`
#569 
Possibly, #410 
Related: #357 
- VS Code settings.json contains `"terminal.integrated.fontFamily": "MesloLGM NF, Hack NF"`
- Powerline theme works:

Fix ps installer

---

font-patcher

https://github.com/ryanoasis/nerd-fonts/blob/bc4416e176d4ac2092345efd7bcb4abef9d6411e/font-patcher#L416-L419
It seems that the `elif` block is meant to check the case where:
- `--removeligatures` is set
- AND no config file is provided.
I guess those blocks are over-indented? For now, no warning or info message is printed even in the very case.

font-patcher: remove_ligatures() never displays warnings

---

font-patcher

Add Caskyadia Mono to RFN replacements.
Add Caskyadia Mono to RFN replacements.
Manually patch Cascadia Mono, the font should be renamed to Caskyadia Mono.
#601
#601
Test results at https://github.com/BiscuitTin/nerd-fonts/actions/runs/1451664880.

Add Caskyadia Mono to RFN replacements

---

patched-fonts/FantasqueSansMono/Bold-Italic/font-info.md
patched-fonts/FantasqueSansMono/Bold-Italic/readme.md
patched-fonts/FantasqueSansMono/Bold/font-info.md
patched-fonts/FantasqueSansMono/Bold/readme.md
patched-fonts/FantasqueSansMono/Italic/font-info.md
patched-fonts/FantasqueSansMono/Italic/readme.md
patched-fonts/FantasqueSansMono/Regular/font-info.md
patched-fonts/FantasqueSansMono/Regular/readme.md
patched-fonts/FantasqueSansMono/font-info.md
patched-fonts/FantasqueSansMono/readme.md
readme_cn.md
readme_es.md
readme_fr.md
readme_it.md
readme_ja.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md
src/unpatched-fonts/FantasqueSansMono/README.md

Update some markdown files about Homebrew cask option.
At latest homebrew version, cask option was changed from "brew cask install  **" to "brew install --cask **"
In this PR(https://github.com/ryanoasis/nerd-fonts/pull/552), only readme.md has changed .
Update some markdown files.
https://github.com/ryanoasis/nerd-fonts/pull/552

Update command about Homebrew cask option

---

font-patcher

**[why]**
When the font file is not existing the message we get is either
unreadable or misleading (at least for normal users).
**[how]**
Explicitly state why we can not open a font file, at least in the cases
where we can.
Improve error messages on font open fail.
Try to patch a non-existing font file. Try to patch a write-only file.
https://github.com/ryanoasis/nerd-fonts/issues/512#issuecomment-981716897
With this MR:

font-patcher: Give meaningful error messages on trivial open fails

---

font-patcher

**[why]**
With a source font where Win Ascent/Descent differs from Typo
Ascend/Descent newly added symbols that are intended to be centered
_within the visual space_ can end up too far up or down.
The happens for example when patching CascadiaCode. Added glyphs like
the Ubuntu logo (unicode 0xF31B) is not centered between the square
brackets or on a line with the less then and other centered glyphs.
**[how]**
The calculation takes the Win Ascent/Descent to calculate the visual
hight. That information is a mix of hight and line spacing and can be
misleading.
Therefore, if use_typo_metrics is set in a font, we obey that flag
and use the typo metrics values instead.
**[note]**
Some websites with further information follow.
https://github.com/googlefonts/gf-docs/tree/main/VerticalMetrics
> …

font-patcher: Use correct source font metrics

---

font-patcher

**[why]**
With commit
f7d6fcb5 `font-patcher: Allow processing of fonts with fsType set`
we added support for fonts with the fsType set. This came up in
issue #686 with font 'Bicubik'.
The solution in that commit uses (modern) textual flags in the
`fontforge` open() method. But they have been only introduced in 2020,
so people using older `fontforge` could not patch anything anymore.
This has been reported in issue #691.
As a quick fix the fsType support has been removed with commit
ab6fa3c5 `Reverts part of #687 * the patcher refuses to patch all/most fonts with this flag in the open options`
**[how]**
Revert ab6fa3c5 but use the old fashioned numerical open flags
interface instead.
**[note]**
The textual open() flags have been introduced into `fontforge`s python
interface with their …

font-patcher: Reintroduce fsType fix

---

font-patcher

**[why]**
The Nerd Font Version is not added to the SFNT Version.
This is also a TODO item in `font-patcher`.
The SFNT-Revision is not updated at all.
**[how]**
Set the SFNT Version and Revision.
Set the SFNT Version and let the SFNT Revision be recreated.
`TODO` item in `font-patcher`
none
Here the font is patched first with the `origin/master` version of `font-patcher` and afterwards with this MR applied:
Note the difference in Revision and the changed SFNT Version string.
`query_version` is one of several small `fontforge` helper scripts I use, maybe they should/could be …

font-patcher: Set SFNT Version

---

font-patcher

**[why]**
When we overwrite a glyph that originally had some special handling, be
it a substitution or position table entry (GPOS/GSUB), that special
handling is usually not appropriate anymore and has to be removed.
If we need special lookup table entries for the new glyph we would have
to add them later anyhow, because we can not rely on their existance.
In Issue #509 it was a ligature entry, that replaced 'f' followed by 'i'
with the 'fi' ligature. The ligature glyph is overwritten by us with a
telephone symbol and the substitution table entry makes no sense
anymore.
**[how]**
If we overwrite a preexisting codepoint we remove it from all lookup
tables.
Thanks to all other reporters with details.
Fixes: #509 #254
Reported-by: mangelozzi <mangelozzi@gmail.com>
Signed-off-by: Fini Jastrow …

font-patcher: Remove obsolete metadata on glyph exchange

---

font-patcher

**[why]**
Sometimes fontforge returns `None` for `font.path`. That should not be the
case according to specs:
```
font.path
(readonly) Returns a string containing the name of the file from
which the font was originally read (in this session), or if this
is a new font, returns a made up filename in the current directory
named something like “Untitled1.sfd”. See also font.sfd_path.
```
This seems to be the case for fonts that do not have a `fullname` set.
I did not search for nor file any issue at Fontforge.
**[how]**
In fact we already have the original font file name, and we want to
retain its extension anyhow (if nothing is specified), so we use the
filename that we opened to determine the extension.
**[note]**
Related: #412
Related: #641
**[note]**
This was the sole usage of font.path. …

font-parser: Allow patching without --ext

---

patched-fonts/DroidSansMono/font-info.md
patched-fonts/DroidSansMono/readme.md
patched-fonts/Ubuntu/Bold-Italic/font-info.md
patched-fonts/Ubuntu/Bold-Italic/readme.md
patched-fonts/Ubuntu/Bold/font-info.md
patched-fonts/Ubuntu/Bold/readme.md
patched-fonts/Ubuntu/Condensed/font-info.md
patched-fonts/Ubuntu/Condensed/readme.md
patched-fonts/Ubuntu/Light-Italic/font-info.md
patched-fonts/Ubuntu/Light-Italic/readme.md
patched-fonts/Ubuntu/Light/font-info.md
patched-fonts/Ubuntu/Light/readme.md
patched-fonts/Ubuntu/Medium-Italic/font-info.md
patched-fonts/Ubuntu/Medium-Italic/readme.md
patched-fonts/Ubuntu/Medium/font-info.md
patched-fonts/Ubuntu/Medium/readme.md
patched-fonts/Ubuntu/Regular-Italic/font-info.md
patched-fonts/Ubuntu/Regular-Italic/readme.md
patched-fonts/Ubuntu/Regular/font-info.md
patched-fonts/Ubuntu/Regular/readme.md
patched-fonts/Ubuntu/font-info.md
patched-fonts/Ubuntu/readme.md

**[why]**
In some fonts, on in the `patched-fonts/` directory the font information
files contain an explanation why the font is called "Terminess" and not
"Termius" - but the font is neither.
Affected: `DroidSansMono` and `Ubuntu` (non mono)
I assume this is a 'I copied the info file over from an existing font
and just change the names' (but the source was unfortunately Terminess).
**[how]**
Manually remove the paragraph from all files that contain it which but
have another name altogether.
**[note]**
Not shure if they are autogenerated somehow, with for example
`standardize-and-complete-readmes.sh` ... but a `git grep` showed only
the files that are changed with this PR.
- `./font-patcher …

font info: Remove references to 'Terminess' from non-Terminus fonts

---

font-patcher

**[why]**
Some of the patched Mono fonts do not turn up in the font chooser
of Windows `CMD` and `PowerShell` (and probably more).
**[how]**
For some reasons Windows does not identify the fonts as being strictly
monospaced, so they are hidden in that font choosers.
For the monospaced fonts we set now the Panose proportion 'monospaced'.
Windows seems to honor the Panose properties.
It is not clear why we need to set the old Panose props, especially as
Cascadia Code does not (!) set them and is still detected as monospaced.
Anyhow, the way Windows detects if a font is monospaced is a mystery (at
least for me), and this works, so ;-)
- `./font-patcher Inconsolata.otf --fontawesome --octicons …

font-patcher: Improve 'Mono' compatibility with Windows

---

font-patcher

**[why]**
This is a TODO item. Well, two in fact.
The `symbolFont`'s selection is used for two things
- the main loop to iterate over all glyphs to insert
- to select the one glyph that is actually copied over
Because the main loop uses iterators on the selection.
The iterator is not 'stable' but invalidates if the selection
is changed.
The current code therefor restores the old selection before the loop
jumps to the head again.
This design is not very robust.
[how]
We need the selection to copy the symbol glyph.
But we can rewrite the loop that it does not need the selection at every
iteration, but that the selection is copied into a list, and we loop
over that list - which is independent on a later selection state.
Remove two `TODO` items.
Patch one font with and one without this PR. …

font-patcher: Copy selection instead of continuously regenerating

---

font-patcher

**[why]**
When a True Type Collection file (`.ttc`) is used as font source this is
not handled and just the first file in the collection is processed and
saved. But the user is not informed.
When the target file format is True Type Collection, **no file at all** is
written.
These are two distinct cases, because you can in fact open a `.ttc` and
save the first font (patched) when specifying a different extension via
`-ext`. Or open a normal font and specify `ttc` as extension i.e. target
file format.
**[how]**
Check if a collection is to be opened. As we currently have no code to
loop through all fonts (and just the first font is processed) a message
is issued and we exit. Typically a user would want all the fonts and
would have to 'explode' the collection into multiple single font files …

Handle TTCs gracefully

---

bin/scripts/gotta-patch-em-all-font-patcher!.sh

The `gotta-patch-em-all-font-patcher!.sh` assumes that it's being run from inside `bin/scripts`, by setting source and target directories according to the output of `pwd`.
That's not super obvious from the outside. When I tried running it, I didn't know and tried running it from the root dir. That didn't cause an error, but instead the script simply didn't find any fonts.
Now it sets the directories relative to the script directory, which allows running it from anywhere.
Added one line plus comment to the script, to set the script directory (var `sd`). Then changed the two instances of `${PWD}` to instead use `${sd}`.
Run the script from inside *or* outside `bin/scripts`, see if it works. I'm currently running it from the root dir, and it's working fine so far.

Allow running gotta-patch-em-all from any dir

---

font-patcher

**[why]**
In ligature-enabled environments the accent grave will be rendered as
zero width, thus overlapping with the next character (in some source
fonts).
The problem is, that the glyph type in the sourcefonts is set to 'auto',
and fontforge exports these as 'mark' - the patched font will be broken.
**[how]**
There is no way we can get that glyph to be 'auto', but we can force it
to be an ordinary 'baseglyph' instead, and that will be respected on
export.
Maybe I should raise an Issue at fontforge... maybe later.
Fixes: #858
Fixes: #582
Always set the glyph type of `grave` to 'just a normal glyph'.
Use some patched font in a ligatures enabled environment, e.g. Writer, Word, VisualStudio, ... type in one "`" and the cursor should advance one slot. …

patcher: Fix grave (backtick) zero width

---

bin/scripts/gotta-patch-em-all-font-patcher!.sh

**[why]**
When the file names of the source files change which happened for example
with these commits:
```
ac432eb20 Updated Inconsolata source to latest upstream version of 2.001 (WIP #289)
9c5ad2c78 Updated Inconsolata source to latest upstream version of 2.001 (WIP #289)
```
or the patched font files naming changes because of any other reason (*):
The patched-font directory will contain the new files along with the
unchanged old ones (because they where not overwritten).
Typically when manually updating the patched-fonts this is not a
problem, as the maintainer can clean this up by hand (if it is noticed).
But with a github action we might want to have that automatized.
To not deter the usability of the script for end-users or for patching
single fonts of a collection we do NOT want …

patch-em-all: Purge destination dirs if possible

---

font-patcher

**[why]**
The 'monospace' width is determined by examining all the 'normal' glyphs
and taking the widest one.
'Normal' means `0x00`-`0x17f`: the Latin Extended-A range.
Unfortunately Noto has the '1/2', '1/4', '3/4' that are all wider then the
normal (i.e. letter) glyphs.
**[how]**
Exclude a small sub-range from the 'find the widest glyph' that contain
no glyphs one would call 'letter'.
Fix `Noto * Nerd Font Mono` variants.
* #610

Fix Noto too wide

---

Dockerfile

The Alpine Linux package repository no longer contains the `fontforge` package for x86 and ARM architectures in the `edge/testing` branch, as can be verified here:
[https://pkgs.alpinelinux.org/packages?name=fontforge&branch=edge&repo=&arch=&maintainer=](https://pkgs.alpinelinux.org/packages?name=fontforge&branch=edge&repo=&arch=&maintainer=)
This commit updates the `nerdfonts/patcher` [Dockerfile](https://github.com/ryanoasis/nerd-fonts/blob/master/Dockerfile) to install the `fontforge` package from the `edge/community` branch to resolve the failing Docker builds.
Modifies the [Dockerfile](https://github.com/ryanoasis/nerd-fonts/blob/master/Dockerfile) so that the `RUN` command reads:
```dockerfile
RUN apk update && apk upgrade && apk add --no-cache fontforge …
```

Fix Failing Docker Builds

---

.github/workflows/docker-release.yml
.github/workflows/font-patcher.yml
.github/workflows/release.yml
bin/scripts/gotta-patch-em-all-font-patcher!.sh

This fixes the problems with _Iosevka_.
----
This PR also contains some CI fixes to get release 2.2.0 running.

Use fontforge 2022

---

bin/scripts/lib/fonts.json

[why]
Lilex is missing from the 2.2.0 RC and is not automagically patched.
[how]
Add Lilex to the font metadata database :->
[note]
Lilex's licence has no RFN given.
Add Lilex to the Ci processes.
Run the CI
#474

CI: Add Lilex to release

---

.github/workflows/font-patcher.yml
font-patcher

**[why]**
Some fonts set specific lower resolutions and handle the small rendering
very nicely. But fontforge does not copy that information when it opens
a font; rather some default values are always written. That can destroy
the small font rendering.
The responsible settings are the `ppem_to_int` flag and the
`lowestRecPPEM` setting, both in the `HEAD` table.
**[how]**
After successfully patching and generating the new font we copy that
settings over from the source font.
Instead of using [`fontTools`](https://fonttools.readthedocs.io) (and thereby requiring all users to pull that
dependency) we handle the raw font file changes ourselves.
Fixes: 612
Reported-by: @nojus297
All these information is given in Issue #612 but a lot other fonts are also affected.
For example
```
fontforge …
```

Feature: correct small rendering

---

.all-contributorsrc
CONTRIBUTORS.md
patched-fonts/Hasklig/readme.md

The patched Hasklig font was updated to use Hasklig v1.2 in d4d8d9e184a487fd92412ff639b79b0d61908b91, but the readme was not updated. This PR updates the readme with the appropriate information found [here](https://github.com/i-tu/Hasklig/releases/tag/v1.2).

Update Hasklig readme

---

font-patcher
readme.md
readme_cn.md
readme_es.md
readme_fr.md
readme_hi.md
readme_it.md
readme_ja.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md
src/unpatched-fonts/NerdFontsSymbolsOnly/config.cfg

This reverts commit 59c45ba4eff539d2a83a7d7004f056b9860d3253.
In the following **_The Commit_** means the commit that this PR want to revert (remove).
**[why]**
_The Commit_ breaks the non-mono Nerd Fonts for a lot of people.
The issue which is the reason for _This Commit_ was not very good documented and investigation can not be
seen.
From _The Commit_'s TITLE it should have affected the 2048-em Symbols font only, but in fact all patched fonts were changed.
Maybe that was intended, maybe not.
**[how]**
This will make the advance width again equal for all glyphs.
This enables the use of the non-mono variant in more terminals.
For wider symbols a space is now (again) needed after the symbol.
That is expected by a lot applications.
Make Non-Mono Nerd Fonts monospaced but allow added symbols …

font-patcher: Make Nerd Fonts Monospaced Again

---

font-patcher

**[why]**
When the fontforge python bindings are not installed we fail while
importing `psMat`. The message suggests that fontforge itself is not
installed - which is not the real reason. One can use the `libfontforge`
with the `python-fontforge` without having the GUI program `fontforge`.
Furthermore we link to outdated installation instructions.
**[how]**
We already check and report correctly what needs to be done with the
fontforge module import. As both modules are often in the same package
we should probably report the same message. That message holds correct
hints for Debian/Ubuntu. It does not have a link to fontforge, though.
**[note]**
Also update Debian package name.
Fixes: #725
Reported-by: Aniket Teredesai <a@aniketteredesai.com>

font-patcher: Correct python module missing message

---

font-patcher

**[why]**
Sometimes the basic glyphs (`[a-zA-Z]` etc) are constructed in the font
from other glyphs via references. To keep those basic glyphs intact we
must not touch the referenced glyphs.
**[how]**
Crate a list of all glyphs referenced by the basic glyphs.
When patching in some new symbol - if that codepoint is in the list do
not overwrite it. Overwriting would break a basic glyph.
The user does not get the glyph that we would have patched in, but that
can not be helped if we want to keep the basic glyphs intact and not
'redesign' the complete font.
Fixes: #400
Do not overwrite codepoints that are needed (by reference) by glyphs in the basic latin range.
Font: `Input Mono`
The ordinary small `j` is a combination of the dotless-small-`j` and a single dot. We must not touch any of the …

font-patcher: Do not overwrite glyphs that are needed for basic glyphs

---

font-patcher

**[why]**
When one wants to use a custom symbol font and specifies it with an
absolute path, the `glyphdir` is still prepended.
That means that the argument to `--custom` is always used as relative
path (to `--glyphdir`), even when it starts with `/`. That is somehow
unexpected or at least inconvenient.
Example:
`fontforge font-patcher --custom ~/Downloads/fa6.otf Inconsolata-Regular.otf`
`fa6.otf` is searched for in `./src/glyphs/home/username/Downloads`
**[how]**
Use Python function that handles joining path fragments.
> If a component is an absolute path, all previous
> components are thrown away.
Allow (respect) absolute paths specified with `--custom`. No change for relative paths.

font-patcher: Allow to specify custom symbolfont with absolute path

---

font-patcher

**[why]**
Some symbol fonts might come with glyphs that have multiple codepoints.
When we want to patch them with `'Exact': true` (i.e. at their 'original'
codepoints) we want to patch them into the codepoint that has been used
in the selection process. That means between `SymStart` and `SymEnd`.
But this is not the case. We patch them in into their 'main' codepoint,
which can be outside the expected range of points.
This came up when patching with FontAwesome V6. It has for example these
glyphs:
Glyph 'music' has a main codepoint `0x1F3B5`, but it is present in the
font also on codepoint `0xF001`.
Glyph 'heard' has a main codepoint `0x1F9E1`, but it is present in the
font also on codepoints `0x2665`, `0x2764`, `0xF004`, `0xF08A`, `0x1F499`, ...
When doing a `'Exact': true` patch (i.e. …

font-patcher: Allow glyphs with altuni for exactEncoding

---

font-patcher

**[why]**
Sometimes the patched-in symbols are slightly too big, which shows up in Nerd Font Mono fonts where the destination size is specified exactly.
That issues a warning like:
```
Warning: Scaled glyph U+F077 wider than one monospace width
```
**[how]**
For the `scaleGlyph` groups we need to combine the bounding boxes of several symbol glyphs to determine the 'combined' scale we need. Unfortunately when the concrete glyph is finally copied over its size can change minimally.
So we need to measure the glyphs in the `scaleGroup` _after_ they have been copied to the to-be-patched font. This is a bit complicated, because we need to know some glyph slot we can use for that.
**[note]**
See also commit
e805b879  `font-patcher: Resolve rounding error when rescaling`
Fixes: #917

font-patcher: Fix scaleGlyph related rounding error

---

install.sh

This is about the `install.sh` script
* Remove defunct options to install non-Complete font variants
* Add option to remove all installed fonts (installed by this script)
Add uninstall possibility to install script.
One can specify `--remove -L` for a dry run to see the commands that would be executed.
#407

install.sh --remove

---

font-patcher

**[why]**
Someone might want to patch a whole lot of fonts that come in a ttc.
**[how]**
Just open all fonts that the input file contains (1 or more) and create
a single font or collection font file.
The automatic layer detection does not work in all cases for me, so we
need to manually search for the foreground layer (usually '1').
Code inspiration taken from
https://github.com/powerline/fontpatcher/pull/6
**[note]**
Changed output in the end to the filename (before it was the font name),
so that one can easily copy&paste or open that file.
Reported-by: Lily Ballard <lily@ballards.net>
Add possibility to 'batch patch' True Type Collections and store the result again in a TTC.
The first 3 commits just juggle around the existing code without (\*cough\*) functional changes. These changes …

Feature: Process TTC files

---

font-patcher

**[why]**
Bitmaps existing in a font are discarded. The font-patcher script just cares about outline fonts.
**[how]**
If the sourcefont has bitmaps, do save them into the patched font. Note that this does not generate bitmaps for the patched-in glyphs (icons).
**[note]**
Fonts probably affected in src/unpatched-fonts:
```
bitmap (11,) (gohufont-11)
bitmap (14,) (gohufont-14)
bitmap (11,) (gohufont-uni-11)
bitmap (14,) (gohufont-uni-14)
bitmap (7, 9, 10, 12, 14, 18, 24) (ProFontIIx)
bitmap (12, 14, 16, 18, 20, 22, 24, 28, 32) (TerminusTTF-Bold Italic-4.40.1)
bitmap (12, 14, 16, 18, 20, 22, 24, 28, 32) (TerminusTTF-Bold-4.40.1)
bitmap (12, 14, 16, 18, 20, 22, 24, 28, 32) (TerminusTTF-Italic-4.40.1)
bitmap (12, 14, 16, 18, 20, 22, 24, 28, 32) (TerminusTTF-4.40.1)
```
Fixes: #86
Reported-by: …

font-patcher: Preserve existing bitmaps

---

install.ps1

Introduces a `-WindowsCompatibleOnly` switch parameter to the existing `install.ps1` PowerShell script to allow a user to specify the installation to only include font files labeled as "Windows Compatible" (as in the font file name contains the explicit string "Windows Compatible").
Implements `-WindowsCompatibleOnly` parameter for `install.ps1` and includes example within the help comments in same file
On a clean Windows machine (no nerd-fonts installed), invoke `PS> .\install.ps1 FiraCode -WindowsCompatibleOnly` with/without `-WhatIf` parameter
Closes #840

Feature: Add -WindowsCompatibleOnly switch parameter to install.ps1

---

readme_cn.md
readme_ru.md
readme_tw.md

Fix the logo source path in *cn* and *tw* documentation.
Fix the logo source path in *cn* and *tw* documentation.

docs: fix logo image source path

---

font-patcher

**[why]**
We just ignore specified gaps in the source fonts (i.e. set them to zero). This reduces the line spacing in the patched font (because the gap is missing).
**[how]**
Distribute the gap INTO the cell, so that we can work with zero gap (we need that for the powerline glyphs), and still keeping the powerline glyphs centered about the regular glyphs AND keeping the total line spacing.
Idea-by: Tushar Singh <tusharvickey1999@gmail.com>
Fixes: #850
Reported-by: Joe Bolts
* #850
See Issue.

Draft: font-patcher: Respect gap values in source font

---

font-patcher

**[why]**
For some fonts the calculated checksum(s) was wrong.
**[how]**
Misplaced the multiplier ... the LSB shall not be shifted of course, but the current code shifts as last action: Also the LSB is shifted.
First shift (old) accumulated content, then add new data. In that way the last added data (LSB) is not shifted.
Noticed only after failed runs on `v2.3.0-RC` because that version number changed the font lengths :eyes:

font-patcher: Fix checksum algo

---

font-patcher
src/unpatched-fonts/NerdFontsSymbolsOnly/NerdFontsSymbols 1000 EM Nerd Font Complete Blank.sfd
src/unpatched-fonts/NerdFontsSymbolsOnly/NerdFontsSymbols 2048 EM Nerd Font Complete Blank.sfd

Fix empty `Symbols Only Nerd Font Mono` fonts.
* Make the empty-input-font detection more robust (such that the empty font may have linegap defined)
* Remote the linegap from out symbols only font templates
Create a symbols only `Mono` variant and look at the glyphs. Are they existing and scaled ok?

Bugfix Symbol Only Mono fonts

---

bin/scripts/archive-fonts.sh
bin/scripts/gotta-patch-em-all-font-patcher!.sh
patched-fonts/Monoid/Bold/complete/LICENSE
patched-fonts/Monoid/Italic/complete/LICENSE
patched-fonts/Monoid/Regular/complete/LICENSE
patched-fonts/Monoid/Retina/complete/LICENSE
patched-fonts/NerdFontsSymbolsOnly/complete/LICENSE
src/unpatched-fonts/Monoid/LICENSE
src/unpatched-fonts/NerdFontsSymbolsOnly/LICENSE

In the release archives (`zip` files) for some fonts the license file is missing.
This fixes this hopefully for the future.
Autogenerate and keep up to date the license files in `patched-fonts/`.
Add `OFL.txt` to possible (recognized) license files.
Add more license file variations to archives.
Complete CI release run and look into all `zip` files, for example
```
find archives -name "*.zip" -exec echo {} \; -exec unzip -l {} \; | grep 'Archive|li.en|LI.EN|OFL'
```
This lists archive names and license files; there shall be no archive name without a following license file.
* #463 
* #468 
Fixes: #979

Bugfix licenses in archives

---

.github/workflows/docker-release.yml

Refactor docker-release (aka build and push) workflow to use the standard Docker Github Actions.
This adds the following features:
- Builds for both AMD64 and ARM64 (other architectures can be enabled if required).
- Automatic tagging and labelling (including 'latest').
- I don't have access to _your_ Docker hub credentials so wasn't able to test I could publish as your user, just check it does successfully publish with your creds the first time (but it should be fine!).
I went to run the nerd-fonts patcher and found the provided container image was only built for  AMD64, many modern computers are ARM64 hence this PR.
https://github.com/marketplace/actions/build-and-push-docker-images

feat: use standard Docker build Actions, enable builds for ARM architecture

---

font-patcher

**[why]**
When a custom set is to be patched and that set contains the `.notdef` glyph the script crashes.
**[how]**
The glyphs has an unicode codepoint of -1, a code that we explicitely not patch. That leads to confusion when we try to determine the codepoint to be used for that glyph, because it has none.
Exclude negative codepoint glyphs when we determine the selection of to-be-patched glyphs.
As last resort for broken custom sets skip over glyphs that come out of order (which should be impossible).
Fixes: #1005
Allow patching with custom sets that contain the `notdef` glyph.

font-patcher: Fix crash on some custom sets

---

readme.md

Adds details on availability of Nerd Fonts via the Chocolatey and Scoop package managers.
Updates the README to include details about unofficial Nerd Fonts availability via Chocolatey and Scoop.
N/A
I learned that Nerd Fonts were available using the package managers in #1013. Prior to this issue, I thought the only option for Windows users was the manual one.
N/A
N/A

doc: Add details on installation via Chocolatey and Scoop

---

.github/workflows/casks.yml
.github/workflows/release.yml
bin/scripts/README.md
bin/scripts/fetch-archives.sh
bin/scripts/generate-casks.sh
bin/scripts/lib/fonts.json

Automatize homebrew cask updates in releases.
* Update the `generate-casks.sh` script to produce modern updates of the existing casks
* Without changing the (sometimes strange) cask name
* With sorted `font` clauses to make autogenerated update diffs be small
* Hook that into the CI workflows
* We need a homebrew fork in the organization
* Push changed files to our fork
* Autocreate PR at homebrew
I guess we will have a manual trigger too, but testing is of course hard(er) because we do not want to generate rouge PRs in some other project :grimacing:
#1003 
https://github.com/Homebrew/homebrew-cask-fonts/pull/6649

Automatize casks update on releases

---

src/unpatched-fonts/Iosevka/config.cfg

**[why]**
The Iosevka font has a lot of different families. A lot users install just all "Iosevka Nerd Font" families, and this can break in a lot different ways.
I will try to collect Issues possibly caused by this in PR #1019.
**[how]**
Just turn the feature on in `font-patcher` (via patch-em-all's config).
Enable `--makegroups` for Iosevka on release runs.
For example in Gnome Terminal, this is how all the Iosevka Families are shown at the moment:
And this is after this PR has been pulled:
Note that the `Nerd Font` part is missing in the 'now' screenshot :-o This not even breaks all the patched Iosevkas, because they mix up all families, but also interfere with parallel installed Iosevka-original :-(

Fix Iosevka Family names

---

font-patcher

The filename is determined by the font (family) name. The font name might include characters that are forbidden to use in filenames.
Filter output filesnames and prevent any character that is likely forbidden under Windows.
Also prevent control characters.
Translate Windows path separators to posix.
Fixes: #632
Replace problematic chars from the output filename with an underscore `_`

font-patcher: Sanitize output filenames

---

font-patcher

**[why]**
fontforge is not really able to work with OpenType variable fonts, at least not with all. Some support is available as MM, for older formats. But anyhow we do not really create a patched variable font but a fixed font.
People might ignore all the errors Fontforge throws on opening, so an explicit message might be in order.
[how]
It is not possible to detect a VF input font with current fontforge reliably. Instead we search for the existence of one of the tables that are  needed for a variable font. We can not rely on `STAT`, because that might be also used in fixed fonts.
Fixes: 512
Just add a warning when trying to patch a VF.
Patch a normal (static) font, patch a VF font.
#512

font-patcher: Warn if sourcefont is a VF

---

font-patcher

**[why]**
The 'monospace' width is determined by examining all the 'normal' glyphs and taking the widest one.
'Normal' means `0x00`-`0x17f`: the Latin Extended-A range.
Unfortunately Overpass (Mono) has wide-as-two-letters `IJ` and `ij` ligatures.
**[how]**
Exclude a small sub-range from the 'find the widest glyph' that contain these ligatures. Yes they will kind of break, but what can we do if we want to create a strictly monospaced font?
[note]
Related commit
fbe07b8ab  Fix Noto too wide
Related: #1043
Exclude IJ and ij ligatures from the width calculation (for NFM), as they are too wide in the supposed to be `monospaced` font `Overpass Mono`.

font-patcher: Fix some Nerd Font Mono too wide

---

bin/scripts/gotta-patch-em-all-font-patcher!.sh
font-patcher

For non-single fonts (i.e. with no `--mono`) added symbol glyphs will be scaled down to be maximum 2 'slots' wide.
Usually the added Glyphs are about 1.6.. 1.8 the width of the normal 'Letters' we have in the target fonts. But there are tiny/tall fonts, where the added glyphs just look out of place.
The first commit refactor the code with no effective change in result. This is needed in preparation to the actual intended change that would look rather complicated otherwise.
The actual change in the 2nd commit allows downscaling added glyphs in non`-mono` fonts, but still observes the `ScaleGlyph` data.
Fonts patched with `--mono` should come out unchanged.
Fonts patched without `--mono` but higher EM value (i.e. where the added symbols are smaller than 2 times the normal advance width) …

Feature: Allow symbol scaling in nonmono (down to 2 'widths')

---

bin/scripts/name_parser/FontnameParser.py
font-patcher

**[why]**
Sometimes we set an empty string as SubFamily name. That ends up as 'Book' which is unexpected.
**[how]**
The translation from empty to "Book" is done by Fontforge, at least with version 20220308.
Make sure we always have a SubFamily, and if we don't that must be a 'Regular'.
**[note]**
This was only a problem with the old naming engine. `--makegroups` got this right always.
Fixes: #1046
https://github.com/ryanoasis/nerd-fonts/pull/780#issuecomment-1381067808

font-patcher: Fix unexpected 'Book' SubFamily

---

font-patcher

[why]
With commit
99c260831  font-patcher: Fix more 'Nerd Font Mono' too wide
the glyphs 'ij' and 'IJ' are exempted from the advance width calculation, because some fonts (i.e. Overpass Mono) defines them as two cell wide glyphs (Hello? 'Mono'?)
For some obscure reason it was 'IJ' and 'J circumflex' that were exempt, not 'ij'.
[how]
Exempt correct code.
Fixes: #703

font-patcher: Fix: Fix more 'Nerd Font Mono' too wide

---

font-patcher

**[why]**
The initial font-patcher used the WIN font metrics to determine the cell    
height. What has been found was forced into HHEA metrics but without    
observing the USE_TYPO_METRICS flag.    
That has been changed to use the TYPO metric instead of the WIN metric    
when the font wants that. For that the gap value becomes important.    
This is the current code. It still has problems to detect the correct    
cell height. A more rigorous approach seem to be needed.    
**[how]**    
The baseline to baseline distance is what we need as 'cell height', to    
fill it completely with the powerline glyphs. This is a little bit    
complicated and not really specified, each font rendering application or    
engine can handle the font metrics differently. But there are some    
common …

Rewrite font height calculation

---

font-patcher

**[why]**
As described in [this comment](https://github.com/ryanoasis/nerd-fonts/issues/400#issuecomment-1397371200), issue #400 recently reoccurred with the latest build of Input font, and it turns out the dotless-j part of the small `j` now points to `U+0237`, which in turn has an alternate unicode encoding to `U+F6BE`; overwriting `U+F6BE` effectively overwrites `U+0237`, and in turn, alters the small `j`. This patch aims to fix that.
**[how]**
In addition to references, the patcher also checks for alternate unicode encodings which are returned by the `glyph.altuni` attribute, adds those to the essential set of glyphs, and in turn recursively searches for their references/alternate unicode encodings, making sure to handle circular references if they appear (for example: `U+2010` and …

font-patcher: Cover alternate unicode encodings

---

bin/scripts/generate-css.sh

This changes the design of the Cheat Sheet, to allow handling the > `FFFF` code points more comfortably for the users.
See
* #1059
This PR also consists of these commits to branch `gh-pages`:
* bae34d36a `cheat-sheet: Copy UTF16 instead of raw hex code`
* 6e361d40c `cheat-sheet: Allow click to copy on hex value`
* 8914909ad  `Regenerate Cheat Sheet`
Go to the cheat sheet and try to copy the UTF16 and hex values (use `-md-` icons for UTF16).

cheat-sheet: Add tooltip to copy hex code

---

readme.md
readme_cn.md
readme_es.md
readme_fr.md
readme_hi.md
readme_it.md
readme_ja.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md

No need `--cask` param to install cask via brew.
```sh
brew tap homebrew/cask-fonts
brew install font-hack-nerd-font
```

No need --cask params anymore

---

readme.md
readme_cn.md
readme_es.md
readme_fr.md
readme_it.md
readme_ja.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md

**[why]**
All/most fonts are now available as Arch Community packages and not as AUR anymore.
**[how]**
Instead of listing all individually link to search page. Make sure the Symbols Only font in Community is also found.
Fixes: #1057

Update Arch package links

---

font-patcher

**[why]**
When a certain 'higher codepoint' glyph is needed for a substitution or ligature rule of a basic glyph and we replace the 'higher codepoint' glyph with a symbol that stylistic set or ligature will be broken.
**[how]**
We can not determine if a certain glyph is the _target_ of a pos-sub rule (at least I could not find a way). What we do is remove all pos-sub entries that _start_ at a symbol-patched glyph [1], but that is not the same.
Instead of walking through all substitution tables we just examine the 'basic glyphs' and also protect all glyphs that they reference through most of the possub tables.
In fact I encountered only "Substitution" entries and never "Ligature" entries, but we handle both alike. "Pair", "AltSub", and "MultSub" are not handled, but could be added if need …

Do not destroy ligs or SS

---

install.sh

**[why]**
The implode function can not work correctly because the bash pattern expansion inserts blanks in unexpected places.
**[how]**
Use a dump loop instead of being smart.
Fixes: #280
Reported-by: Geoffrey Biggs <gbiggs>
Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>

install.sh: Fix installing more than 2 fonts

---

bin/scripts/generate-font-image-previews.sh
bin/scripts/lib/fonts.json

**[why]**
Some font previews in the `gh-pages` are obviously wrong (showing some fallback font).
[how]
Recreate all image previes from current `master` branch.
To make this more easy:
- Add commented out code that displays command to install just the needed fonts but all the needed fonts
- Add commented out code that displays the family names of the needed fonts - these have to be in sync with the `fonts.json` database
Fixes: #489
Reported-by: CosmosAtlas
Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>
Change the preview generator script to enable its users easier preview generation.
The code is commented out (for laziness reasons). If you need instructions how to install the needed fonts _on my machine_ ;-) or how their family names are, uncomment that code.

Fix font previews

---

bin/scripts/generate-css.sh

**[why]**
The (old) Material Design Icons are to be removed. We should communicate that on the Cheat Sheet.
**[how]**
See commit
4452ceee5  `Add possibility to add "obsolete" to glyphs`
that implements the CSS stuff to display an 'obsolete' marker.
Change the cheat-sheet generatot to actually insert the markers for the appropriate codepoints. That is, the codepoints are not checked but the ID.
Fixes: #1096
Before:
After:

Mark old MDI as obsolete on cheat sheet

---

font-patcher

**[why]**
When changes are made to the `font-patcher` and fonts are patched with that version we can not see which patcher has been used in the fonts afterwards.
Would be good to have the usual version-patchversion number in the fonts in these cases (i.e. `v2.3.3-7` for 7 commits after `2.3.3`).
I did this manually before, but it is always a hassle.
[how]
If the `font-patcher` is run directly from a git repo and git is installed we try to get the latest tag version including patch number.
If and only if that is successful and that version is 'newer' than the version encoded in the `font-patcher` script the git version is trusted more.

font-patcher: Use git version tag for font version

---

font-patcher

**[why]**
Instead of redistributing the line gap we remove it. At least when HHEA or TYPO metrics are used.
It's ok with WIN metrics.
**[how]**
If we have negative numbers for a gap and want to add more to it, where 'add' means 'make it more', we must of course _subtract_ the value.
But baseline-to-baseline code into function so we can check it after all our gymnastics for correctness. It means the metrics.
**[note]**
Also correct out-of-sync comment.
Fixes: #1116
Reported-by: Nathaniel Evan <nathanielevan>
Fix wrong gap removal on HHEA and TYPO metrics fonts. Was ok on WIN metrics fonts.

font-patcher: Fix line gap redistribution

---

font-patcher

The `nf-custom-asm` and `nf-custom-v_lang` icons are present in the [css file](https://github.com/ryanoasis/nerd-fonts/blob/master/css/nerd-fonts-generated.css) and [database script](https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_seti.sh), but not in any patched fonts. Also, in the [cheat sheet](https://www.nerdfonts.com/cheat-sheet) they are displayed as blank rectangles since glyphs are not available (see below).
This PR fixes the `font-patcher` script to include these glyphs in font.

font-patcher: Make sure nf-custom-asm and nf-custom-v_lang icons are included

---

readme_cn.md
readme_es.md
readme_fr.md
readme_it.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md

**[why]**
Python 2 is long since EOL.
With the last commit we want to use Enums, which are not available in Python 2.
I believe Python 2 broke some time before already, I stopped caring for Python 2 some time ago.
This does not change any existing code. It just documents that there are no efforts anymore to support Python 2.
This is PR #1121

Drop support for Python 2

---

bin/scripts/generate-original-source.py
font-patcher

Allow for growing original icon set    
**[why]**
We have an automation for adding glyphs to the original set.    
If someone throws in the svg file and adds the glyph to the icons.tsv a    
new original-source font is generated.    
But the added glyphs are not patched in, because that would need a    
change at font-patcher (adjust the end codepoint).    
This can be forgotten easily.    
**[how]**
The maximum codepoint of our own (original + seti) set is 0xE6FF. At    
0xE700 the Devicons start.    
The original-source generation script now checks the offset, they may    
not be negative and on the positive end we may not leave our set-range.    
If that happens the script fails thus the workflow fails.    
Also increate the patch range in font-patcher. If there are no icons to …

Allow auto original source growth

---

font-patcher

**[why]**
The Powerline extra glyph sizing is not really clear.
**[how]**
* Make the triangulars 1 cell wide, as for example Iosevka also does.
* Make the Legos 2 cell wide with pa scaling to make them look nicer.
* Make the Hexagons 2 cells wide and keep their aspect ratio if possible.
* Make small and big Squares also 2 cell wide and keep their aspect ratio
of possible.
For the small and big Squares add a tiny bit of border (negative
overlap), because they have no smooth border line over their open and
closed squares, and that might look strange if some touch and some dont.
Fixes: #1106
Will follow

 Reform PowerlineExtra sizing

---

font-patcher

The clouds in the weather icons are all scaled individually.
This makes it hard to exchange one for the other when the weather changes.
Also a problem are the moon phases, all the increasing phases are shifted a bit to the left?!
This PR fixes both issues with one commit each.
Fixes: #1107

Fix weather icon scale and shift

---

.github/workflows/release_master_fontpatcher-zip.yaml
.github/workflows/zip-release.yml
bin/scripts/archive-font-patcher.sh

Fixes https://github.com/ryanoasis/nerd-fonts/issues/1040
@all-contributors please add @b- for infra
- Adds a Github Actions workflow to release _just_ an updated fontpatcher.zip from master, upon push of font-patcher or its dependencies or glyphs to master 
- make sure the freshly cooked font-patcher.zip contains all required dependencies (but not anything else), and functions as expected.
https://github.com/ryanoasis/nerd-fonts/pull/1041
https://github.com/ryanoasis/nerd-fonts/issues/1040

Release master fontpatcher

---

font-patcher

[why]
When the font has no name the patching fails.
When there is no name we fall back to filename parsing, so it should not fail.
[how]
Check if we have a name. If not do not try to set it.
[note]
Also change type checks to isinstance() calls.
Fixes: #514

font-patcher: Allow anonymous fonts

---

font-patcher

**[why]**
The Material Design Icons have for sure pairs of glyphs that people would like to have scaled identically. Because the sheer number of glyphs and because they are already very nicely and uniformly scaled within their design space the MDI at the new codepoints where all scaled the same with taking the theoretical design space as ScaleGlyph.
But that means all icons get scaled a bit smaller than before, where we individually scaled each Material Design Icon to fill the cell. This lead to numerous complaints.
**[how]**
We take a different approach now, more conventional maybe. Especially in the light that the older bigger icons will get dropped; and people love them.
So the uniform scaling is ditched and the individual scaling is used.
Fixes: #1061 …

font-patcher: Scale all Material Design Icons individually

---

font-patcher

**[why]**
All glyphs of the codicons set are individually maximised in size. That leads to the curious condition that 'circle small' looks bigger than 'cicrle' (because the line width is scaled up more -> looks bold).
Also some other 'subsets' look ugly and can not be used together.
**[how]**
Add appropriate ScaleGroups.
For the circles we also include one full-size circle as reference. To get less than maximal scale for the small circles.
Scale some Codicon icons down (i.e. not up to fill the cell), in `Nerd Font Mono`.
https://github.com/ryanoasis/nerd-fonts/issues/448#issuecomment-1451808965
Left side: before, right side: after.
Note that the small arrows (circled) are rather big instead.

Add Codicons scale list

---

font-patcher

[why]
If a font has references in glyphs that we want to add to the essential set of glyphs, and fontforge is old (i.e. 2020*) the patcher crashes.
[how]
The fontforge function glyph.references returns a three element tuple in current fontforge (i.e. 20230101). But older versions skip the selection bit and return only tuples of two.
As we use only the first tuple element we do not care about the 2nd and possible 3rd element(s) and just thrash them.
Fixes: #1142
Fix running `font-patcher` on older `fontforge`

font-patcher: Fix crash with older fontforge

---

bin/scripts/generate-font-image-previews.sh
bin/scripts/lib/fonts.json
readme.md
src/unpatched-fonts/Iosevka/copyall.sh
src/unpatched-fonts/IosevkaTerm/LICENSE.md
src/unpatched-fonts/IosevkaTerm/README.md
src/unpatched-fonts/IosevkaTerm/config.cfg
src/unpatched-fonts/IosevkaTerm/copyall.sh

**[why]**
Both are full fledged families, one specifically for terminal, the other not. Although it might be that people want both there is a likelyhood that some just need one set.
Splitting these makes the individual release packages smaller and more handable, and improves release workflow run time.
See also #803

Disentangle Iosevka and Iosevka Term

---

readme_cn.md

Fix the bug of anchor point failure in documents

Fix the bug of anchor point failure

---

font-patcher

**[why]**
Some old applications seem to depend on obsolete `xAvgCharWidth` values to
show two-cell glyphs correctly. Fontforge can only generate OS/2 tables
version 4, but these applications need 2 or less. In fact they seem to
not look up the version number, but rely on the value being like it
always has been ;-)
One example is Windows `notepad`, that takes the `xAvgCharWidth` as base for
the cell size and draws the two-cell chars in a cell twice that size -
without any regard to glyph width.
**[how]**
These issue seems to be encountered rather seldom and only with some
obscure (grin) applications. There is also no good way to handle this
automatically. So we add a command line option that allows the user to
tweak the value after patched-font generation.
The option is called …

Option to manipulate xAvgCharWidth

---

site.js

This pull request fixes copying codepoints on the cheatsheet. It looks like the previous version of the code was one node off in terms of how many parents it traversed which resulted in the first codepoint always being copied, instead of the one that the user clicked on.
Fixes copying of the codepoint from the bottom right corner of the character box on the cheat sheet page of the website.
Start the website with `jekyll s` and verify that copying codepoints on the cheatsheet now works, whereas it did not before these changes.
---
I assume I'm just supposed to make this change directly to the gh-pages branch, but if that's not right, lmk what branch I should be targetting instead.

Fix codepoint copy

---

font-patcher

[why]
Any non-monospaced font will not be be patched, the patcher crashes.
[how]
This must have happened when the box drawing characters rescaling feature has been disabled. The default value (False) is not always set.
The box drawing patch has the ability to rescale existing box glyphs. That used to be done when all box glyphs are already existing in the source font. We do not patch in a new glyph set then, but we rescale the existing glyphs to match the possibly new cell size. But that feature is disabled and the attribute 'dont-copy' is never utilized. It is disabled because some existing box sets are rather ... sspecial in their overlap and can not be scaled as we would scale them.
Fixes: #1170
Reported-by: Henrique Monteiro <hrqmonteiro@protonmail.com>

font-patcher: Fix patching non-monospaced fonts

---

.github/workflows/font-patcher.yml
bin/scripts/lib/fonts.json
bin/scripts/name_parser/FontnameTools.py
font-patcher
readme.md

[why]
The license of Bitstream Vera requires patched fonts to contain neither "Bitstream" nor "Vera" in the name. It explicitly requires that also for fonts that (only) add some glyphs.
Yes, we are rather late to notice this :-( Sorry.
[how]
Rename Bitstream Vera to BitstromWera, and also drop the Sans Mono part of the name. The new name looks and sounds similar enough to get the reference, while being shorter and somewhat logical.
Fixes: #1173

Rename Bitstream Vera (due to RFN)

---

bin/scripts/gotta-patch-em-all-font-patcher!.sh
font-patcher
src/unpatched-fonts/Lekton/README.md
src/unpatched-fonts/Lekton/config.json
src/unpatched-fonts/Noto/README.md
src/unpatched-fonts/Noto/config.json
src/unpatched-fonts/OpenDyslexic/README.md
src/unpatched-fonts/OpenDyslexic/config.json
src/unpatched-fonts/Overpass/Mono/config.json
src/unpatched-fonts/Overpass/Non-Mono/config.json
src/unpatched-fonts/Overpass/README.md
src/unpatched-fonts/SpaceMono/README.md
src/unpatched-fonts/SpaceMono/config.json

**[why]**
Some sourcefonts, even that are monospaced, have a `fi` and/or `fl` ligature that maps into one cell. That looks very strange.
**[how]**
Partially revert commit
148b0c445  Sunset ligature removal
for the cases that have a one-cell `fi`, `fl`, etc ligature, or a `ldot` related ligature - that is active by default. Discretionary ligatures or Stylistic Sets are not changed.
Do the removal on all patched fonts for consistency, not just `Nerd Font Mono`.
**[note]**
On Noto different subtables are needed for Sans, Serif and Sans-Mono. We can not set up different configs for each, so all are tried in all fonts and might fail (this is normal).
Fixes: #1187

Prepatched fonts: Revive some ligature removal

---

font-patcher

[why]
On some fonts the patcher tries to raise a warning, but it can not.
[how]
The 'overlap' variable can hold a floating point number or be None (if there shall be no overlap processing. Formerly we output that value using the {} format, but the logging module does not have that. To accomodate to different types use repr() instead.
[note]
Also improve some other logging related calls.
Reported-by: Jim Myhrberg <contact@jimeh.me>

font-patcher: Fix logging related warning

---

bin/scripts/gotta-patch-em-all-font-patcher!.sh
font-patcher

The `font-patcher` always logs the debug messages in a file.
That fails when `fontforge` is an AppImage (and maybe when we are a docker image?)
This PR drops that feature. Logging to file has to be explicitly requested with a parameter to the `--debug` option.
Introduce parameter to --debug option.
0 = no debug output
1 = log to file only (previously always selected)
2 = log to stdout only
3 = log to file and stdout (previous default for --debug)
Just specifying --default equals now --debug 2.
The gotta-patch-em runs now with --debug 1.
Reported on Gitter by @loveFluffy - Thank you for the report!

Bugfix logging on AppImage

---

readme.md

font installation process option 6 broken link fix

fix broken link readme.md

---

font-patcher

[why]
The Box Drawing glyphs need to be carefully scaled. This can not be done if the glyphs are pulled in via font-fallback I guess.
As people may have the fontconfig set up in a way to prefer the Symbols Only font these glyphs could overrule other box drawing glyphs that might fit better.
I'm not really sure about this one, but the glyphs look rather bad anyhow, because they end up in the 1:1 ascpect ratio cell of the Symbols Only font.
[how]
Just turn the set off if we patch the Symbols Only font. Need to swap around two subroutine calls for that; first detect if we are patching the Symbols Only font (through the font metrics) and then set the patch sets up.
Fixes: #1210
Drop the box drawing glyphs from the Symbols Only font(s).
They have been introduced with 3.0.0

font-patcher: Drop box-drawing from SymbolsOnly

---

font-patcher

This changes how custom patching (i.e. with `--custom`) is handled.
When I tried to use the feature myself several shortcomings became obvious.
This is mostly triggered by @siduck 's problem
* https://github.com/ryanoasis/nerd-fonts/issues/1213#issuecomment-1539214446
* https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1532632029
* #1207

Improve custom patching

---

font-patcher

font-patcher: Fix vanishing fi ligature
[why]
With Ubuntu-Regular the fi and fl ligatures are replaced by some font
awesome icons.
The problem is that the font uses the non-standard F001 and F002
codepoints as intermediate referencve to create the actual ligatures
that are at codepoints FB01 to FB04.
[how]
All the normal ligature codepoints (FB00-FB06) are added to the glyph
reference checker and codepoints that are referenced by these are not
patched.
This means that F001 and F002 stay on the original ligatures and the
Font Awesome icons are missing, but this can not be fixed automatically
and would need to 'rewrite' the references inside the font.
Fixes: #1221

Bugfix ligatures in ubuntu

---

bin/scripts/README.md
bin/scripts/generate-sample-set.sh
bin/scripts/gotta-patch-em-all-font-patcher!.sh
font-patcher

**[why]**
The added heavy brackets are maximized within the cell size as all
normal other symbols. But in fact they should not be maximized but
rather be the size of 'normal brackets'.
Furthermore they are all scaled individually, making the size
differences less.
With some proportional fonts the brackets look tiny.
**[how]**
Introduce new y-padding parameter (because a negative overlap also acts
in x direction, what we do not want (and it distorts)).
Pad the brackets with 30% (15% top and 15% bottom).
This is used for all fonts (monospaced or not) so that the new glyphs
fit nicely with the existing ones. For some definitions of 'nicely', but
that is as good as we can get with automatism. It's not worse than
font-fallback.
Fixes: #1229
Fixes some bug fixed along the way :grimacing: …

font-patcher: Do not maximize heavy brackets in Mono

---

bin/scripts/name_parser/FontnameParser.py
font-patcher

**[why]**
For fonts that have no Italic but an Oblique - i.e. when Oblique shall replace the Italic role in RIBBI font grouping (classic group of 4) - that grouping fails.
This affects DejaVu on Putty.
**[how]**
For RIBBI grouping only the classic bits are considered. That means that for fonts that have Oblique instead of Italic (and not additionally) we need to set the ITALIC bit and the OBLIQUE bit. This has been overlooked.
Cite from the specs:
> This bit, unlike the ITALIC bit (bit 0), is not related to style-linking
> in applications that assume a four-member font-family model comprised
> of regular, italic, bold and bold italic. It may be set or unset
> independently of the ITALIC bit. In most cases, if OBLIQUE is set, then
> ITALIC will also be set, though this is not required. …

FontnameParser: Fix fsSelection for --has-no-italic

---

bin/scripts/name_parser/FontnameParser.py
bin/scripts/name_parser/FontnameTools.py
font-patcher

**[why]**
Patching CartographCF-Bold.ttf creates this naming:
Family (ID 1)      : CartographF Nerd Font Condensed
SubFamily (ID 2)   : Bold
Fullname (ID 4)    : CartographF Nerd Font Condensed Bold
PSN (ID 6)         : CartographFNF-CondensedBold
PrefFamily (ID 16) : CartographF Nerd Font
PrefStyles (ID 17) : Condensed Bold
CartographF Nerd Font Condensed Bold
\===> 'CartographFNerdFont-CondensedBold.ttf'
**[how]**
The font-patcher historically used the file name of the to-be-patched font to come up with the new name. When the FontnameParser has been developed that mechanics has been copied at least for fallback. The earliest tests compared old and new naming with all the filenames.
Later, when the FontnameParser has been used to really apply name changes it has always based the parsing …

name-parser: Remove filename parsing code and more

---

_posts/2017-01-07-release.md

I think the `</div> </details>` at the end of the v3.0.1 release notes was being parsed as part of the last `<li>` item, resulting in `</div> </details>` being escaped. This PR should fix the issue where in the HTML output, the v3.0.1 release `<details>` included the release notes for v3.0.0, v2.3.3, etc.
Adds a new line after the last list item and before the `</div> </details>` in the changelog post for GH Pages.
The issue on https://www.nerdfonts.com/releases:

Fix changelog formatting

---

bin/scripts/data/cheatsheet-foot.txt
bin/scripts/data/cheatsheet-head.txt
bin/scripts/generate-css.sh

modify `generate-css.sh` for changes in #1252

---

font-patcher

Revert scaling of (most of) the Codicons back to individual maximize as it has been with `v2.3` and before.
On the way a new Scaling method is introduced and removed again as it does technically solve the problem but probably people do not want relative consistency but big icons i.e. maximizing.
Fixes: #1240

Bugfix Codicon Circles

---

bin/scripts/test-fonts.sh

_The line decorations are hardcoded to 5 elements, with these changes you just need to change the `wrapAt` varible and the line decorations length will change as well_
Change the printing method of decorations.
Just change `wrapAt` variable and execute the script.
The default value wastes a lot of usable space in the terminal.
Example with length of 16 elements.

test-fonts.sh: allow wrapping at any number

---

.github/workflows/release.yml
bin/scripts/archive-fonts.sh

archive-fonts: Create tar.xz packs

---

font-patcher

Add a flag for the user to not-rename (not touch) the name fields.
This can be useful for Visual Strudio and Cascadia Code, see https://github.com/ryanoasis/nerd-fonts/issues/1242#issuecomment-1575490749
See description.
Also corrects some logic errors (that do not really have an effect, but are nonetheless wrong).
Are in the issue.

Allow not renaming the font with parameter

---

font-patcher

Python complains about error on line 1881 in font-patcher.
Maybe you guys should take the time to check if the function `global logger` is doing exactly the right thing.
Fix typo in font-patcher.
I'm not sure, maybe this feature isn't finished yet?
Python complains about error when I manually patch fonts.
The shell script I use is:
```
for p in ../iosevka-custom-mono/ttf/*.ttf; do
echo -e "Patching for font \e[0;36m${p:27}\e[0m ..."
fontforge -script font-patcher "$p" -cq --careful -out iosevka-custom-mono-nerd --makegroups 0
done
```
When I do not set the parameter `--makegroups 0`, it reports an error.

Fix logging error font-patcher

---

_includes/css/nerd-font-tweaks.scss
cheat-sheet.js

- Fix having multiple vertical scrollbars
- Update icons lazy loading accordingly
Fix having multiple vertical scrollbars while searching the icons, it's easier to use and better for User Experience. It's also update the lazy loading to work on the document scrolling instead of icons container

Update search page style

---

bin/scripts/archive-fonts.sh
src/archive-readme.md

**[why]**
The readmes in the zip and tar.xz archives differ. The zips have only a very small and generic `readme.md`. The tar.xz have that readme as well as the `README.md` from the patched-fonts/ directory. This should be the same for both.
To have two files with names that just differ in case (`readme.md` and `README.md`) can be problematic on some platforms.
**[how]**
Combine both readmes into one file - put the generic info in the top of the readme.
Also include the RELEASE_VERSION if known into the readme. That makes it more easy to identify which Nerd Font release that archive came from.
RELEASE_VERSION is set in the release workflow.
Fixes: #1284
Reported-by: Jan Klass <kissaki@posteo.de>

archive-fonts: Unify README handling

---

font-patcher

font-patcher: Add option to select postscript name as name source
**[why]**  
In the post we used these information sources to determine the name and
weights/styles of the to-be-patched font:
* The filename
* The fullname (ID 4)
* The postscriptname (ID 6)
Usually it is best to use the Fullname of a font to determine its real
name and styles/weights:
The Postscript name has the advantage to have a hyphen between name and
styles/weight; but as it can not contain blanks the correct name can not
be determined by this. To get the styles/weights back we use a list of
all possible (?!) weights and styles and sort all the string parts.
This works reasonably well and the fullname is usually best.
Not so with Input Mono Condensed. Here are its names:
ID4: `"InputMonoCondensed LightIta"`
ID6: …

Feature: Select name source

---

readme.md
readme_es.md
readme_hi.md
readme_ru.md
readme_tw.md

Gives read-write access to the volumes. See https://web.archive.org/web/20190728100417/https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/
See also this issue for more details: https://github.com/ryanoasis/nerd-fonts/issues/1347
Update Readme
Run docker command with the proposed change
https://github.com/ryanoasis/nerd-fonts/issues/1347

Add ":Z" options to volume mounts

---

bin/scripts/name_parser/FontnameParser.py
bin/scripts/name_parser/FontnameTools.py
font-patcher

[why]
Windows seems to construct the font names including the PS weight. We have some sourcefonts that are broken (i.e. have in fact different weights but have the same PS weight and/or OS2 weight.
That raises problems with the fonts on Windows.
[how]
Check and compare all weight metadata (except CID) and issue a warning if they differ too much. That might fail with unusual weight names, though.
See Issue #1333 and PR #1358.
Reported-by: LeoniePhiline
Did let it run over the complete repo with
```console
$ NERDFONTS="--dry --debug 3" ./gotta-patch-em-all-font-patcher\!.sh
$ grep -i -A 1 parse ../../font-patcher-log.txt
$ grep -A 1 Possible ../../font-patcher-log.txt
```

font-patcher: Introduce weight check

---

install.sh

**[why]**
When a user sets the `XDG_DATA_HOME` environment variable the default of `$HOME/.local/share` should not be used.
https://wiki.archlinux.org/title/XDG_Base_Directory
**[how]**
Enable `XDG_DATA_HOME` to override the default user data directory on Unix and MacOS platforms.
There is some controversy if `XDG_DATA_HOME` should be honored on MacOS, see for example platformdirs (link below). But me also working on Linux and MacOS (and Windows) in parallel, I can not quite follow the downsides and believe we should allow `XDG_DATA_HOME` also for MacOS.
Related: https://github.com/platformdirs/platformdirs/issues/4
Fixes: #1324
Suggested-by: Anthony Foglia <@afoglia>
If envvar `XDG_DATA_HOME` is set and the user want to install into a user directory the default path is adjusted …

install.sh: Honor XDG_DATA_HOME

---

readme.md

updated the project's readme to mention that the font patcher CamelCases and removing whitespace from the resulting font's family names.
the change contains GitHub's alert syntax, which might not render in the preview, but should render in the actual readme. (ref: https://github.com/orgs/community/discussions/16925#discussioncomment-6879962)

Describe patcher family-name generation in readme

---

_includes/css/main.scss
_posts/2017-01-02-features.md

To solve the overflow problem of `div.subtitlecircle`, the following CSS has been added:
``` 
@media screen and (min-width: 990px) {
.row .subtitle-icon {
display: flex;
flex-wrap: wrap;
flex-direction: inherit;
}
}
.subtitle-icon {
display: flex;
justify-content: center;
align-items: center;
flex-direction: column;
margin: auto;
flex-wrap: wrap;
}
.container ol, .container ul { 
padding: 0 8%; 
margin: 20px;
}
```
The .subtitle-icon class is added to the parent element (wrapper) of div.subtlecircle, preventing the element from overflowing and aligning it to the center of the features section. The media query is specifically added to resolve the overflow of the Terminal Fonts subtitle icon without creating a new class or adding specific styling(i have reused the css class which i made for …

Solved: Responsive Design div.subtlecircle Overflow on Small Screens (< 767px) #1367

---

bin/scripts/name_parser/FontnameParser.py
bin/scripts/name_parser/FontnameTools.py
font-patcher

[why]
When the font does not have a PSweight string the font-patcher bugs.
[how]
Rewrite the code to be more robust against unexpected weight values. Also make detected problems non-fatal.
Reported-by: František Hanzlík <frantisek_hanzlik@protonmail.com>

font-patcher: Improve weight checking

---

_includes/css/nerd-font-tweaks.scss
_posts/2017-01-01-home.md
index.html

Implemented Solution 2 to address the user experience issue with the "Fork-me" banner on smaller screens. Added a GitHub icon in the bottom left corner with margin and padding. This icon serves as a persistent and easily accessible link to the GitHub repository.
This pull request enhances the user experience by providing a persistent link to the GitHub repository through a GitHub icon in the bottom left corner of the page.
1. Visit the website (https://vitthalgund.github.io/nerd-fonts/).
2. Observe the presence of the GitHub icon in the bottom left corner.
3. Click the icon to ensure it redirects to the GitHub repository (https://github.com/ryanoasis/nerd-fonts).
This PR is a response to issue #1372, which identified an issue with the "Fork-me" banner on smaller screens.
This PR is …

Implement GitHub Icon for Improved Accessibility to Repository - Issue #1372

---

readme.md
readme_cn.md
readme_es.md
readme_fr.md
readme_it.md
readme_ja.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md

The AnonymicePro Nerd Font is incorrectly named Anonymice Nerd Font.

doc: Correct name for AnonymicePro Nerd Font

---

_includes/css/nerd-font-tweaks.scss

As discussed in [Pull Request #1368](https://github.com/ryanoasis/nerd-fonts/pull/1368#issuecomment-1751669936), I've addressed an issue where the circle shrinks horizontally but not vertically. There's also an additional problem with the layout of the entire website where within the Font Patcher script section, the ```<details>``` tag overflows from its parent. This results in a horizontal scrollbar, which disrupts the website's layout. 
I've created this issue to report and address the following problems:
- The subtitle inner circle inside the features section shrinks horizontally but not vertically for screens with a width less than 767px, leading to overflow issues.
- The `<details>` tag within the Font Patcher script section overflows from its parent, causing a horizontal scrollbar …

Issue with Subtitle Circle and Layout on Smaller Screens #1384 fixed

---

bin/scripts/name_parser/FontnameParser.py
bin/scripts/name_parser/query_name
font-patcher

**name-parser: Unify abbreviations in family names**
**[why]**
Because the newer Preferred/Typographic names ID 16 and ID 17 have not
a very demanding length limit we add the long form of the name
addendum (i.e. Nerd Font, Nerd Font Mono, Nerd Font Propo).
In the more restricted old names ID 1 and ID 2 we use the short forms
(i.e. NF, NFM, NFP).
This seems to be problematic with Visual Studio (Community) 2022 and the
fonts can be selected but are not really used.
The Postscript family name is never shortened which seems to be of no
consequence, but still is different than the other.
**[how]**
When creating the Preferred/Typographic Family (ID 16) we check the
shortening mode first and abbreviate the parts as needed and alike ID 1.
This will also change the filenames, because they base on …

Bugfix for Visual Studio 2022

---

bin/scripts/generate-font-image-previews.sh
bin/scripts/lib/fonts.json
readme.md
src/unpatched-fonts/IosevkaTermSlab/LICENSE.md
src/unpatched-fonts/IosevkaTermSlab/README.md
src/unpatched-fonts/IosevkaTermSlab/config.cfg
src/unpatched-fonts/IosevkaTermSlab/copyall.sh

Add Iosevka from Iosevka Release v22.1.1
https://github.com/be5invis/Iosevka/releases/tag/v22.1.1
Keep in mind, patching Iosevka needs corrected `fontforge`.
But that also holds for the already present Iosevkas.
Probably this should be coupled with a general Iosevka update. Here just the `Term Slab` is added, the other two are untouched and an old revision!
Add another Iosevka variant, next to the already present 'standard' and 'Term' ones.
Fixes: #281 see comments in the end esp. for folder structure?

Add Iosevka Term Slab

---

font-patcher

[why]
When we can not detect the cell width, for example because there are no glyphs in the range of extrended-roman that we examine, the width will be zero and that will result in a crash later on (on rescaling).
[how]
Just abort if height or width are zero or negative.
Related: #1460
Add a new (potential) fatal check after determining source font dimensions.

font-patcher: Fix crash if no roman characters

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/devcontainer.json

Updating the `.devcontainer` configuration to latest version.

fix: Latest configuration for `devcontainer.json` and Dockerfile

---

bin/scripts/test-fonts.sh

Added gkpyhs that were missing from test-fonts.sh 
Change the range for the Symbols Original set int the font-test.sh script to include all the glyphs in that set.
This is the Symbols Original set before the change:
And after the change:

fix: added missing glyphs in test-fonts.sh

---

Dockerfile
bin/scripts/docker-entrypoint.sh
readme.md

Improve the docker execution method, optimize from single process to parallel execution, and increase the speed of font patching.
see [issue 1507](https://github.com/ryanoasis/nerd-fonts/issues/1507)
Speed up docker patcher

Parallel execution fontforge in docker

---

bin/scripts/data/cheatsheet-head.txt

Autofocusing the cheat sheet input text on page load would improve some workflows and I doubt would break other workflows.
> I'm not 100% sure I understood the framework, but hopefully this works.
Adds the `autofocus` attribute to the search input field.
See if the search input field is focused automatically on page load

cheat-sheet: Add autofocus on load to search input text

---

bin/scripts/lib/fonts.json
bin/scripts/name_parser/FontnameTools.py
readme.md
src/unpatched-fonts/ZedMono/Extended/config.cfg
src/unpatched-fonts/ZedMono/LICENSE.md
src/unpatched-fonts/ZedMono/Normal/config.cfg
src/unpatched-fonts/ZedMono/README.md
src/unpatched-fonts/ZedMono/update.sh
src/unpatched-fonts/fontfilenames

Added a new font: "Zed Mono"
Adds a new font
https://zed.dev/
https://github.com/zed-industries/zed-fonts/issues/10

Add font Zed Mono

---

font-patcher
src/unpatched-fonts/Ubuntu/README.md
src/unpatched-fonts/Ubuntu/config.json

Remove the `fi`, `fl` etc ligatures from Ubuntu to free that glyphs for overpatching. At the moment two Font Awesome glyphs (music, magnifying_glass) can not be inserted for that reason.
Also fix some code in the patcher that accidentially protected that glyphs albeit no ligatures are active in that font.
Fixes: #1595
Related: #1221

Bugfix Ubuntu ligatures

---

bin/scripts/lib/fonts.json
fonts.json
license-audit.md

Add SPDX license info
[why]
It can be hard to find out which license a particular font is using.
Therefore we add a new field to the fonts.json with an SPDX license
identifier (if possible).
[how]
For fonts with a license that has no SPDX identifier we use a free
`LicenseRef-*` identifier, but that reference is not solved in the
fonts.json file.
[note]
Also correct some licensing info given in the license audit.
Related: #1578
Suggested-by:  Jan Christian Gruenhage <jan.christian@gruenhage.xyz>

Improve licensing info

---

font-patcher

Fixes: https://github.com/ryanoasis/nerd-fonts/issues/1611
Directly copied from https://github.com/ryanoasis/nerd-fonts/issues/1611#issuecomment-2061294859
> Ah, the heavy brackets are now two times shrunken, there was an old rule that already sized them down relative to the full cell:
> 
> ![image](https://private-user-images.githubusercontent.com/16012374/323240564-eff2642b-20af-406f-85a1-6d8e63d648c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MjAzOTMsIm5iZiI6MTcxMzgyMDA5MywicGF0aCI6Ii8xNjAxMjM3NC8zMjMyNDA1NjQtZWZmMjY0MmItMjBhZi00MDZmLTg1YTEtNmQ4ZTYzZDY0OGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0 …

font-patcher: don't double-shrink heavy angle brackets

---

readme.md
readme_cn.md
readme_es.md
readme_fr.md
readme_hi.md
readme_it.md
readme_ja.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md

Remove homebrew cask installation
Remove homebrew cask installation
Yes
Linked in screenshot provided

chore(installation): remove homebrew cask installation as it errors out

---

font-patcher

**[why]**
When the file specified to be patched is not a font file the patcher run errors out with an out of index runtime error:
```
Traceback (most recent call last):
File "/home/fini/extra/git/nerd-fonts/font-patcher", line 2155, in <module>
main()
File "/home/fini/extra/git/nerd-fonts/font-patcher", line 2147, in main
patcher.generate(sourceFonts)
File "/home/fini/extra/git/nerd-fonts/font-patcher", line 415, in generate
sourceFont = sourceFonts[0]
~~~~~~~~~~~^^^
IndexError: list index out of range
```
**[how]**
Do not assume that the specified file will be a font file but rather check if fontforge detects a font in the file and error out if there is no font found.
Fixes: #1647
Reported-by: Kristopher James Kent <kris@kjkent.dev>
Prevent …

font-patcher: Fix behavior when trying to patch non-font files

---

.editorconfig
bin/scripts/README.md
bin/scripts/cheatsheet.sh

_CLI cheatsheet._
Adds a script that let users to search for an icon using its name using the NF library scripts.
```shell
$ ./cheatsheet divider
       e0b0    i_pl_left_hard_divider
       e0b1    i_pl_left_soft_divider
       e0b2    i_pl_right_hard_divider
       e0b3    i_pl_right_soft_divider
       e0d7    i_ple_left_hard_divider_inverse
       e0d6    i_ple_right_hard_divider_inverse
```
There are times when I want to look for a glyph but using the online cheatsheet tool takes "a lot of time". The tool is not slow I mean the whole workflow.

Add CLI cheatsheet script

---

readme.md

This will add some information about an alternative installation method for PowerShell.
Also see discussion here: https://github.com/ryanoasis/nerd-fonts/discussions/1697
Update `README.md` with info about PowerShell web install option.
n/a
n/a
https://github.com/ryanoasis/nerd-fonts/discussions/1697

docs(install): Add PowerShell Web Installer

---

font-patcher

**[why]**
A lot of icons that do not represent a 'weather state' but rather a 'weather event' are in the 'weather state' scaling group which scales the icons waaaay down. This makes those icons almost unusable in stand alone use cases.
**[how]**
Put all the extra icons into a new scaling group that is defined before the weather state scaling group and thus takes precedence.
Split the final scaling group to have some icons on individual scale.
Fixes: #1708
Scale some icons bigger, that are currently in the same scale group as all the clouds and stuff and thus get very small.
* #1708 
Top the weather set with the changed-in-size icons marked with blue background.
Bottom the set before this PR.
_Icons in a Nerd Font Mono variant_

Increase weather icons 'other' icons scale

---

font-patcher

Correct right aligned glyphs in proportional fonts (i.e. `--variable`).
Only very few icons are right aligned, all Powerline glyphs.
* #1695

Fix Powerline glyphs position and size in some cases

---

.all-contributorsrc
CONTRIBUTORS.md

Allcontributors problem.
They created this branch, but no PR.
This seems to be also only partly finished?
#1736

docs: update CONTRIBUTORS.md

---

CONTRIBUTORS.md

Made the all-contributors badge (at the top here https://github.com/ryanoasis/nerd-fonts/blob/master/CONTRIBUTORS.md) update live and changed the color (`orange` → `#ee8449`).
Improves the all-contributors badge in CONTRIBUTORS.md
All in accordance with https://allcontributors.org/docs/en/bot/faq and https://shields.io/badges/git-hub-contributors-from-allcontributors-org

docs: improve contributors badge

---

bin/scripts/archive-fonts.sh
font-patcher
install.sh
readme.md
readme_cn.md
readme_es.md
readme_fr.md
readme_hi.md
readme_it.md
readme_ja.md
readme_ko.md
readme_pl.md
readme_pt-pt.md
readme_ru.md
readme_tw.md
readme_uk.md

At the moment, if you want to have "monospaces" icons you always also force the font to be monospaced in Windows terms.
That has biten us in the past. Maybe It is better to leave that choice to the user and make this two options.
Remove `--use-single-width-glyphs` (to avoid confusion)
Add `--single-with-glyphs` which is analogous to `--variable-with-glyphs` and just affects our added icons.
The old `-s` and `--mono` force any font to be strictly monospaced and also sets the new `single-with-glyphs` option.
* #1772

Add new option to keep original glyphs as is when adding single-width icons

---

font-patcher

Improve Windows as patching OS compatibility by
* allowing absolute path to begin with a drive letter
* assembling path with the system path separator
And finally, for all systems:
* Specify encoding of glyphnames datafile to avoid surprises
Apart from other stuff, allow a drive letter in the `outputdir` parameter:
Example:
```
PS C:\Program Files (x86)\FontForgeBuilds\bin> .\fontforge.exe
--script C:\Users\jastr\Downloads\FontPatcher\font-patcher
--outputdir c:\Users\jastr
C:\Users\jastr\Downloads\Miosevka12.\Font\Miosevka12\Miosevka-Regular.ttf
```
* #1761

Improve patching-under-Windows compat

---

bin/scripts/lib/README.md
bin/scripts/lib/i_all.sh
bin/scripts/lib/i_extra.sh

[why]
The progress indicators can not be found, people need to know that they are there.
The progress indicators (taken from Fira Code) were introduced with #1733 and then moved:
bd5936856  font-patcher: Add progress indicators
41f91bcb4  Combine extraglyphs fonts
But no entry in the cheat sheet has been added. Which is the same for the boxdrawing glyphs and others in extraglyphs, but those other will probably be not searched for.
[how]
Add a new i_*.sh file for the extraglyphs icon set and introduce a new prefix just for the progress indicators to improve discoverability.
Fixes: #1827

Add progress indicators to cheat sheet

---

font-patcher

[why]
The patched fonts in otf format are much bigger than the ttf counterparts. Even when the same font is used as source. The factor is about 2 to 3.5 in size.
[how]
Fonts in ttf format can not store nodes with sub-integer precision. The coordinates are rounded on export. But otf fonts can have real numbers (may it be floating point or fixed point notation, I am not sure right now and it does not matter) for coordinates, but the more precise numbers take much more space in the font file. If an otf is created where the coordinates are already integer this extra space is not needed.
So we do all the calculations with real numbers (including decimals) and only in the last step the coordinates of the added glyphs are rounded to integer (i.e. to the EM size grid).
Fixes: #1848
Issue number …

font-patcher: Create smaller otf files

---

font-patcher

[why]
When the source glyph set is in a monospace group the proportional
scaling creates wrong advance widths and/or alignment.
Note that there are only very few monospace groups (i.e. 2).
[how]
Determine the 'cell' width, which can be one of three values depending
on mode. Use that width whereever a cell width is needed instead of the
fontwide-cellwidth (which might be wrong in proportional variants).
These are all affected in the symbols only font (usually too far right, outside 'cell')

Fix alignment for some glyhs in propo
